### ISSUE TITLE
ContextActivities Property

### ISSUE THREAD

**Issue by GrantBailey** [adlnet/xAPI-Spec#1006]
At 2.4.6.2 of the specification the ContextActivities Property is explained. The section 'Details' (at https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#details-15) outlines the four valid context types of the Context Activities Property, one of which is 'Other' which is defined as 'a contextActivity that doesn't fit one of the other properties'.

Does this mean that 'Other' may be used to nest one ContextActivities object within another? I have not been able to achieve this using the Tin Can PHP library (the 'Other' property only seems to accept an Activity object).

Thank you.

**Comment by brianjmiller** [comment]
See the second bullet in https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#requirements-11. Nesting isn't possible.

**Comment by GrantBailey** [comment]
Thanks Brian, I overlooked it. :-(
