### ISSUE TITLE
Add service for translate documentation

### ISSUE THREAD

**Issue by olegatro** [adlnet/xAPI-Spec#1053]
Hi, can you add crowdin or other service for allow translate documentation.

**Comment by garemoko** [comment]
crowdin looks like something that could be useful for large translation projects involving many people. Right now, having too many people translating the spec is not a problem we have.  

If you'd like to translate it, I suggest create a fork and then create translated copies of the documents in a folder.

**Comment by olegatro** [comment]
Thank you.
