### ISSUE TITLE
Question on Put/Post Statement with statementId parameter

### ISSUE THREAD

**Issue by rasmuseeg** [adlnet/xAPI-Spec#1089]
Hi there,

When POSTing a statement with parameter `statementId`, the resource must respond in the same way as if the statement was submitted using PUT?

If the POST method endpoint received a batch of statement and the parameter `statementId` how should the resource respond?

Thanks!

**Comment by garemoko** [comment]
The statementId parameter is not a valid parameter for the POST method, so I would expect the LRS to return a 400 bad request response is this parameter is used with POST.

**Comment by rasmuseeg** [comment]
Wauh, i can't believe what a huge mistake i just made. 

Thanks, i believe my thoughts was drawn towards the conclusion because of the following live:
`Stores a single Statement with the given id. **POST can also be used to store single Statements.**`

Now i can clearly see that it does not receive any parameters.
