### ISSUE TITLE
LRS Statement table not getting updated in few cases

### ISSUE THREAD

**Issue by yashbant** [adlnet/xAPI-Spec#1091]
We are using Grassbalde-LRS for our multiple courses. But recently we are facing one issue where the statement is getting inserted into gb_activities_state table but not into gb_all_statements table, specially the passed verb.
Also we are not able to login into grassbalde dashboard as its not responding anything. Please let me know if there any limitation issue(no. of statements).

**Comment by vbhayden** [comment]
Morning @yashbant, that seems like an issue with that particular LRS solution and likely not with the spec document itself.  

You can submit a ticket to the Grassblade support team **[through this link](https://nextsoftwaresolutions.zendesk.com/hc/en-us/requests/new)** and they can take it from there.
