### ISSUE TITLE
User activities related statement not getting inserted into statement table

### ISSUE THREAD

**Issue by yashbant** [adlnet/xAPI-Spec#1092]
We are using Grassbalde-LRS for our multiple courses. But recently we are facing one issue where the statement is getting inserted into gb_activities_state table but not into gb_all_statements table, specially the passed verb.
Also we are not able to login into grassbalde dashboard as its not responding anything. Please let me know if there any limitation issue(no. of statements).

Because of that user status is getting updated without completing.

Regards
Yash

**Comment by DataBeeGood** [comment]
@yashbant This is NOT a Grassblade helpdesk.  
Please open a ticket on their site.

[Grassblade support](https://nextsoftwaresolutions.zendesk.com/hc/en-us/requests/new)
