### ISSUE TITLE
State API conclusions from Alexandria

### ISSUE THREAD

**Issue by fugu13** [adlnet/xAPI-Spec#275]
I was looking over the standard, and realized I don't think we incorporated the state API conclusions reached in Alexandria, that values stored with the State API with one authority are invisible to and do not interfere with values stored in the State API from another authority, except when an LRS Is configured (mechanism left up to LRS) to allow two authorities to share state.

**Comment by andyjohnson** [comment]
Per the 9/16/15 call, the TODO list:

1)  Security - future versions maybe, but not for this one.  It is out of scope
2)  There are potential circumstances for disabling any of these resources that could be considered "turned off".  All would need to be on for conformance testing.  Not worth mentioning in the spec.  Need to avoid having an LRS created without having a resource at all.
3-6)  Seems to be profile / user data management, recommend CoP around this.
