### ISSUE TITLE
Should LRS reject statements that contain properties not specified in the spec?

### ISSUE THREAD

**Issue by ivoloshin** [adlnet/xAPI-Spec#335]
So, I see that a user can add any new properties in the extensions object. However, since we are receiving a JSON document, it's possible for extra fields to be included. Should LRS reject those types of statements?

Thanks,
Ilya

**Comment by garemoko** [comment]
Picking this up for PR into section 4.1.12 now:

* Add to the list of statements the LRS MUST reject ```where a key or value is not allowed by the standard.```. this is a bit of a circular requirement, but does make clear the LRS has to validate these things. 
* Add to the client requirements:
    * ```Additional properties SHOULD* NOT be added to statements and other objects unless explicitly allowed and the LRS MAY* reject statements and objects containing such additional properties.```

**Comment by garemoko** [comment]
I'm also replacing "the standard" with "this specification" in my change and the other requirements in this section.

**Comment by garemoko** [comment]
What else does this need to be applied to other than statements? 

* the About object
* the Person object

Anything else?
