### ISSUE TITLE
409 Conflict under 7.1 Error Codes specifically calls out PUT for statements but not POST

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/xAPI-Spec#362]
POST of statements should also be mentioned here (when posting a batch of statements there can still be a conflict, in which case 409 should still be used)

**Comment by garemoko** [comment]
This has since been resolved by https://github.com/adlnet/xAPI-Spec/pull/520 and https://github.com/adlnet/xAPI-Spec/pull/564

I believe this issue can be closed.
