### ISSUE TITLE
Statement API - add GET/POST clarification/example

### ISSUE THREAD

**Issue by victorolinasc** [adlnet/xAPI-Spec#367]
Hello all!

I believe the spec could use some clarification on the Statement retrieval services. There is a very small note saying (int the end of this [section](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#getstatements)): 

> "Due to query string limits, this method MAY be called using POST and form fields  if necessary. The LRS MUST differentiate a POST to add a Statement or to list  Statements based on the parameters passed."

When it says form fields, can we imply that the Content-Type of the POST for retrieval is "application/x-www-form-urlencoded"? If so, it would help to state that on the note. And if that is the case, should we ignore query parameters or consider them both? I believe it is cleaner to consider only form fields as this was the intention in the first place.

Other than that, I guess examples are due. For instance, GET with query paremeters is ok, but JSON in query parameters are a bit more uncommon (at least for me). Form fields with serialized JSON is also a bit more uncommon to me but Agent must be a JSON according to the spec.

Maybe expanding the session with examples would ease understanding.

Cheers,

**Comment by garemoko** [comment]
This can now be closed.
