### ISSUE TITLE
Discrepancy in Verb id responsibility

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#444]
I believe we need to change the "MUST" below to a SHOULD as the previous section's requirement says that a verb IRI SHOULD reference a specific meaning.  This is a patch issue as it clears up a conflict and the requirement is in the right as opposed to the explanatory text.

4.1.3.1 Use in Language and Semantics of Verbs

For example, the English word "fired" could mean different things depending on context, such as "fired a weapon", "fired a kiln", or "fired an employee". In this case, an IRI MUST identify one of these specific meanings, not the word "fired".

**Comment by garemoko** [comment]
This is now resolved in https://github.com/adlnet/xAPI-Spec/pull/529 (not yet merged at time of writting)

**Comment by garemoko** [comment]
I believe this is now resolved by #529 (now merged) and can be closed.
