### ISSUE TITLE
Duration property of the Result object (4.1.5) does not have to comply with alternative format mentioned in ISO 8601

### ISSUE THREAD

**Issue by nashyura** [adlnet/xAPI-Spec#477]
Wikipedia sites: *ISO 8601:2004 clause 4.4.3.3 Alternative format* in making durations like the following valid:
"P0003-06-04T12:30:05”
It introduces the above format saying "Alternatively, a format for duration based on combined date and time representations may be used by agreement between the communicating parties…”.

Since we are referencing the ISO as described by wikipedia and don’t know about how optional this format is in the actual standard doc, and because someone may skim over the part about BOTH parties having to agree, we may want to clarify the Type of Duration in the spec with something along the lines of this:
“The Duration MUST NOT be set to any of the Alternate Formats described in ISO 8601.”

**Comment by andyjohnson** [comment]
Agreed on Jan 7, 2015 call to change this to a MUST NOT due to a) never opting into ISO8601 alternate format (we'd all agree the format is "normal" ISO 8601, not all inclusive) and b) the potentially disastrous effects of the caps on the alternate format.
