### ISSUE TITLE
Section 7.8, Cross Origin Requests, is insufficiently precise

### ISSUE THREAD

**Issue by fugu13** [adlnet/xAPI-Spec#482]
In particular a simple, unambiguous way is not provided to distinguish between headers and GET params. I think a fairly minimal change would be to specify a whitelist of headers that might be found, then require every other parameter to be treated as a GET param, though I'm eager to hear other possible clarifications.

**Comment by garemoko** [comment]
This will be fixed by #566 when merged.

**Comment by garemoko** [comment]
This can now be closed. (IMHO)

**Comment by andyjohnson** [comment]
Agreed that this has been cleaned up thoroughly and anything that may have been missed can be opened as a smaller issue.
