### ISSUE TITLE
Clarification on Immutability

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#484]
In the spec call on August 6, 2014, the topic of immutability was discussed and agreed that some things shouldn't influence it.  

I propose the following addition to section 4.0 - "Changing serialization (e.g. Timestamps and Time Zones, object type) doesn’t change immutability"

The other issue to consider is would this be a 1.1 change?  I think we are okay at 1.0.2, but want the group's opinion.

**Comment by garemoko** [comment]
Going to have a go at PRing this now. 

Also going to tackle the following related issues:

* https://github.com/adlnet/xAPI-Spec/issues/537

* https://github.com/adlnet/xAPI-Spec/issues/576 (which is a pointer for https://github.com/adlnet/xAPI-Spec/pull/529#discussion_r22465223)

**Comment by garemoko** [comment]
This also has some connection with https://github.com/adlnet/xAPI-Spec/issues/485 which is a major change.

**Comment by garemoko** [comment]
Why would signatures be changed?

**Comment by garemoko** [comment]
Question: should the query parameter 'format' affect immutability i.e. if the format is 'exact', can I expect my timestamps to use the original time zone and my group members list to retain its order? The current spec explicitly excludes agent objects from 'canonical' and demands that they are always returned 'exact'.

**Comment by bscSCORM** [comment]
The way it's written, one could make a case for requiring the returned JSON to be pretty-printed if and only if the submitted JSON was. That doesn't seem reasonable, so I think we need to back down from that as we clarify, and I suggest we consider TimeZone and the order of an array in that category. The current wording is a mess.

No reason signatures should change, that doesn't make sense.

**Comment by garemoko** [comment]
https://github.com/adlnet/xAPI-Spec/pull/529 also contributes to this issue in relation to verbs and immutability.

**Comment by garemoko** [comment]
On arrays - do we apply this to all arrays or just the members property of groups? ther arrays include:

* attachments
* correctResponsesPattern
* interaction components
* context activities
* returned statements (which DO have a specific order, so we'd ned to be careful with any blanket wording)
* statement ids when POSTing statements (also order matters)
* Multiple Document GET
* Almost every property of the Person object
* About version list
* IFIs when up-converting from 0.9 (The first item is kept and the others discarded - not sure if this matters)

**Comment by garemoko** [comment]
From call today: make clear that attachments are not part of statements so when statements are returned by an LRS without attachments (GET statements with attachments: false) that doesn't affect immutability.

**Comment by bscSCORM** [comment]
I withdraw my comment about "order of an array", it doesn't make sense as that should be preserved anyway as a property of what an array is.  I think I briefly was thinking of the order of properties within the JSON and misspoke.

**Comment by garemoko** [comment]
I believe this can now be closed.
