### ISSUE TITLE
Definitions Update

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xAPI-Spec#496]
I would like to report a semantic issue with the use of the term "profile" in the spec. Here is the current definition:

Profile: A construct where information about the learner or activity is kept, typically in name/document pairs that have meaning to an instructional system component.

The use of this definition is not in alignment with the intent of profiles within a Community of Practice (CoP) such as in this section:

4.1.3.2 Use in Communities of Practice

Description

Communities of practice will, at some point in time, need to establish new Verbs to meet the needs of their constituency.

Therefore, it is expected that xAPI communities of practice generate profiles, lists, and repositories that become centered on Verb vocabularies. ADL is creating a companion document containing Verbs for xAPI to serve the ADL Community.

---------------------------------------------------

Do we need to re-evaluate our use of the term "Profile" throughout the spec? Seems like everything is a Profile. Can we add a new definition in the spec to reflect the use of "design profiles" in the CoP section? Such as:

 A design profile contains the schema and properties of a specific xAPI use case.  A design profile should result in a reusable template or design pattern that could be leveraged by other xAPI CoPs.

**Comment by garemoko** [comment]
Yes, it seems like we have two distinct uses of the word profile. I think "design profile" is still too close to "profile" as well. 

This is a hard problem because 'profile' in the sense of activity/agent profile is enshrined in resource URLs so can't be changed, but profile in the sense of "CMI5 profile" is fairly well ingrained both into the spec itself and into guides, blogs and resources outside of the spec. On that basis, probably "design profile" as suggest by Jason is the least worst solution.

**Comment by jhaag75** [comment]
There might even be more than two distinct uses. I just search the spec and found usage of the term in these sections:

- Communities of Practice / Domain Specific Profiles (EBooks, CMI-5, SCORM, etc.) 
- Activity & Agent API Profiles
- Extension Profiles
- OAuth Authorization Scope

The definition associated with the "API profiles" should be refined. I think this would help significantly for the meanwhile. Here's the definition in the spec:

Profile: A construct where information about the learner or activity is kept, typically in name/document pairs that have meaning to an instructional system component.

And if we wanted to be more accurate when we talk about CoP profiles, these are really "domain-specific profiles" or use cases. I agree with Andrew in that "design profile" still doesn't really help as it uses the word "profile" still. Too close. 

So we need more than one definition of "profile" to rule them all ;-) I can take a stab at a new definition for CoP/ Domain specific profiles and submit a PR for the areas that should be updated. But can someone else help with the other uses? Or at least double-check to see if it could be described better than just calling it a profile? Does Activity & Agent API really need the term "profile" added to it?

**Comment by jhaag75** [comment]
There might even be more than two distinct uses. I just search the spec and
found usage of the term in these sections:

- Communities of Practice / Domain Specific Profiles (EBooks, CMI-5, SCORM,
etc.)
- Activity & Agent API Profiles
- Extension Profiles
- OAuth Authorization Scope

The definition associated with the "API profiles" should be refined. I
think this would help significantly for the meanwhile. Here's the
definition in the spec:

*Profile*: A construct where information about the learner or activity is
kept, typically in name/document pairs that have meaning to an
instructional system component.

And if we wanted to be more accurate when we talk about CoP profiles, these
are really "domain-specific profiles" or use cases. I agree with Andrew in
that "design profile" still doesn't really help as it uses the word
"profile" still. Too close.

So we need more than one definition of "profile" to rule them all ;-) I can
take a stab at a new definition for CoP/ Domain specific profiles and
submit a PR for the areas that should be updated. But can someone else help
with the other uses? Or at least double-check to see if it could be
described better than just calling it a profile? Does Activity & Agent API
really need the term "profile" added to it?



-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by garemoko** [comment]
We should replace "extension profile" with "Extension". 

The use in OAuth Authorization Scope refers to the Activity & Agent API Profiles.

**Comment by jhaag75** [comment]
I'm working on attempting to articulate this in the upcoming vocab companion spec. I started a mind map with descriptions if anyone would like to contribute. 

https://docs.google.com/document/d/133Y7xPCe5xhDMwCwhy0MSXXF26_mXnSuRo-XcuyCrPA/edit#

**Comment by garemoko** [comment]
Where are we at with this? What needs to happen next to get this issue closed or deferred out of scope for 1.0.3?

**Comment by jhaag75** [comment]
Need to review again for consistency. I would also like to use the
definitions of profile and recipe you and Russell helped with for the vocab
spec. I will try to get this updated and ready for review this week so we
can close out.
