### ISSUE TITLE
Update 4.1.7 and 4.1.8 with Important Info

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#510]
Neither section 4.1.7 nor 4.1.8 outline the behaviors that the table in section 4 portrays.  This information should be added to these sections for ease of use for those referring to those sections and not reading the entire spec.

**Comment by garemoko** [comment]
Does https://github.com/adlnet/xAPI-Spec/pull/567 address this or is there more to do?

**Comment by andyjohnson** [comment]
Still have more to do, now that the other PRs are in the clear, I'll do this one before the meeting on 1/21/15
