### ISSUE TITLE
Attachments: "contentType" must match part's "Content-Type"

### ISSUE THREAD

**Issue by brianjmiller** [adlnet/xAPI-Spec#513]
The spec in 4.1.11 says:

> SHOULD include a Content-type field in each part's header, for the first part this MUST be "application/json".

And we were discussing whether there should be a MUST added such that it states that the content type in the headers of the part *MUST* match the content type as is provided in the statement metadata. There isn't really any other rational choice as far as I know, but being explicit about it, well, makes it explicit.

**Comment by andyjohnson** [comment]
I think we now end up duplicating this requirement in the first and last bullet in the first and last sub-bullet of the referenced text.  I believe we are saying it SHOULD be used, but never actually say anything about it matching.  I'm guessing the matching is also a SHOULD, or would the LRS actually reject something just because the header is wrong.  If the LRS knows enough that the header is wrong, it must know what kind of attachment it is and be able to handle it, so rejection seems silly.

**Comment by garemoko** [comment]
Those requirements relate to the first part which is the statement, whereas I think Brian is referring to the all the other parts containing the attachments. 

I think the LRS should reject statements with attachments where the types don't match as whilst the LRS knows they don't match, it doesn't know which is correct. This will also help with debugging and catching errors.

**Comment by brianjmiller** [comment]
Correct, my concern is that the 'contentType' property as specified in the attachment meta data in the statement matches the 'Content-Type' MIME header of the attached file in the request. The LRS need not even consider the body of the attachment in that case (and shouldn't), and frankly even the AP doesn't have to be *correct* it just has to *match*.

**Comment by andyjohnson** [comment]
as 1/21/15 call we are okay with MUST, will leave it open to SHOULD* if we feel anything else reasonable could be done.

**Comment by fugu13** [comment]
Thinking about it more, I think MUST is pretty important. If they aren't required to match, then we reach the odd situation where clients will just have to decide (probably arbitrarily) which one to trust, which could lead to very inconsistent behavior; that doesn't make any sense as they're both supposed to be the content-type for the content, and the only way to enforce that sensibly is to require they match exactly.

**Comment by fugu13** [comment]
(Note: that's not a call for checking the contents and trying to guess the real content-type/check if they fail to match up, just for letting them be consistently right or consistently wrong if the AP makes a mistake)

**Comment by fugu13** [comment]
I *do* think it is defensible for LRSs to, for example, reject Statements that try to use a bare content-type without required parameters, but that's really just validating the content-type is a real content-type (as they do have required structure).

**Comment by andyjohnson** [comment]
Per the 2/4/2015 call, very rare usage of attachments in the wild.  @garemoko in PR #608 goes beyond just the matching of type and states all attachment parameters and properties MUST match.
