### ISSUE TITLE
ID not in url for "PUT Statement"

### ISSUE THREAD

**Issue by ryansmith94** [adlnet/xAPI-Spec#514]
I'm just wondering why the `id` of the statement is not at the end of the URL like `http://example.com/xAPI/statements/{id}` (see [7.2.1](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#721-putstatements)). This is a RESTful convention and I don't see why this specification would try to go against that particular convention. I'm sure there is a reason, I just don't see it right now.

**Comment by garemoko** [comment]
Reading through this, it seems the outstanding question/proposal here is to remove the PUT method from the Statement API. This would be a major change, so I suggest we update the tag to reflect that and save this to discuss later.

**Comment by ryansmith94** [comment]
100% agree that PUT should be removed. We already have a way to add statements to an LRS with or without an `id`. There is no need to have another way to do it.

I think the [principle of least privilege](http://en.wikipedia.org/wiki/Principle_of_least_privilege) is useful here.

**Comment by garemoko** [comment]
I'm very glad you agree as this was my attempt to summarise your earlier comment(s) ;-)

**Comment by brianjmiller** [comment]
I'm still :-1:, and I don't think principle of least privilege applies since this isn't a security issue. Security is always at odds with ease of use, that doesn't mean it should win, especially in cases where security isn't at play. I recall the days when we did everything with POST, I realize it may be a stretch, but if we go that direction we can still even with the spec do everything with POST, that doesn't make it a good idea.

**Comment by ryansmith94** [comment]
I wasn't referring to the security aspect, I was referring to the fact that we should provide only the information and resources that are necessary to store statements. Anything more is a waste of resources.

**Comment by liveaspankaj** [comment]
I strongly believe that PUT should be deprecated, or at least people should be encouraged to use POST.

**Comment by ryansmith94** [comment]
+1 @liveaspankaj

**Comment by andyjohnson** [comment]
Per the 1/21/15 call - Closing this issue as it relates to the issue already referenced.  We can open a separate issue on the deprecation of PUT as a 2.0 issue.

**Comment by ryansmith94** [comment]
Nice sounds good.
