### ISSUE TITLE
Structure of return value for POST Statements

### ISSUE THREAD

**Issue by canweriotnow** [adlnet/xAPI-Spec#517]
This is a severe ambiguity (oversight?) that I hope we can get fixed in 1.0.3, it's relatively minor as changes go but major as far as impacting the ability to create sane APs.

[Section 7.2.2 POST Statements](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#722-poststatements) specifies that a successful request returns: "200 OK, Statement id(s) (UUID)."

One issue here is that it doesn't specify the structure of the JSON response body. LearningLocker and other LRSs return a bare array (not inside a valid JSON Object. Our own initial implementation did the same because no object/document structure is specified in the POST spec.

This is problematic for a number of reasons. 

1. This is inconsistent behavior from GET statements, which returns an object with the array of statements as the value for the key, i.e.

```json
{
  "statements": [
    {
      "object": {
        "objectType": "Activity",
        "id": "http://example.org/activities/clickingfoo",
        "definition": {
          "description": {
            "en-US": "The click of a foo button"
          },
          "name": {
            "en-US": "clicking foo"
          }
        }
      },
      "verb": {
        "display": {
          "en-US": "experienced"
        },
        "id": "http://adlnet.gov/expapi/verbs/experienced"
      },
      "id": "87848dec-be6d-4188-8758-8570fc2d7840",
      "timestamp": "2014-10-24T14:43:35Z",
      "version": "1.0.2",
      "stored": "2014-10-24T14:43:36Z",
      "actor": {
        "objectType": "Agent",
        "name": "Foo Bar",
        "mbox": "mbox:foo@example.org"
      }
    },
    {
      "object": {
        "objectType": "Activity",
        "id": "http://example.org/activities/clickingbar",
        "definition": {
          "description": {
            "en-US": "The click of a bar button"
          },
          "name": {
            "en-US": "clicking bar"
          }
        }
      },
      "verb": {
        "display": {
          "en-US": "experienced"
        },
        "id": "http://adlnet.gov/expapi/verbs/experienced"
      },
      "id": "cec90ee1-0b70-43b1-a350-bdd971c61651",
      "timestamp": "2014-10-24T14:43:34Z",
      "version": "1.0.2",
      "stored": "2014-10-24T14:43:34Z",
      "actor": {
        "objectType": "Agent",
        "name": "Foo Bar",
        "mbox": "mbox:foo@example.org"
      }
    }
  ],
  "more": "/xapi/statements?page=1&as-of=2478&limit=2"
}
```

Now, in theory we wouldn't want the entire statement bodies returned (question on this later), but wrapping the array in an object for the sake of consistency just seems like good practice.

So a POST could return

```json
{ "statementIds":
    ["cec90ee1-0b70-43b1-a350-bdd971c61651",
     "87848dec-be6d-4188-8758-8570fc2d7840"]
}
```

You get the picture.

2. More importantly than consistency, sending bare arrays without an enclosing object is murder on most strict JSON parsing libraries. Google's gson, for instance, freaks out if there's no object to parse back into a Java object:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
```
Other parsers have the same issue; RESTful endpoints are supposed to return _resources_, I'm not sure it's really in the spirit of REST to return a naked array and call it a resource

3. I'm not sure how many folks here are following the [JSON API Spec](http://jsonapi.org/) but it's emerging as a general standard for JSON APIs and a set of best practices for JSON resource representation.

The very first MUST in that spec is:

A JSON object MUST be at the root of every JSON API document. This object defines a document's "top level".

Tangentially related question: If an AP POSTs multiple Statements expecting the LRS to generate the UUIDs, and receives the array of UUIDs back, how does it know which one identifies which statement? If there's no mechanism for this, the whole thing becomes moot, I think, and a successful POST could just return a `201 Created` or `202 Accepted` without a body.

**Comment by garemoko** [comment]
Is this now resolved based on https://github.com/adlnet/xAPI-Spec/pull/523 ?

**Comment by andyjohnson** [comment]
I'm good with this, @canweriotnow do you want this left open for more 1.0.3 work, re-labelled for 1.1, or closed?  Thanks!

**Comment by andyjohnson** [comment]
Closing for 1.0.3, can re-open upon request for future versions .
