### ISSUE TITLE
Clarify UUID format

### ISSUE THREAD

**Issue by nashyura** [adlnet/xAPI-Spec#535]
RFC 4122 allows for multiple variants of the GUID format, with only one being officially described in the spec (Variant 2).  The other variants do not really seem like they would be used in the proper generation of a UUID for a Tin Can Statement.  As such, it may be a good idea to clarify where the xAPI spec stands regarding this.  Do we accept all possible variants including ones that don't yet exit, do we only accept GUIDs formatted according to Variant 2, or something in the middle?  Adhering strictly to variant 2 would allow LRSs to at least do a cursory validation of the GUIDs they are processing by checking the bits representing variant and version.

**Comment by ryansmith94** [comment]
Any reason why the changes in this PR are no longer part of the spec?

**Comment by garemoko** [comment]
They are in the development version of the spec now found at: https://github.com/adlnet/xAPI-Spec/tree/1.0.3

Master branch now shows the latest *published* version of the spec, 1.0.2. 

Sorry for the confusion; this will be better for everybody in the long run!

**Comment by ryansmith94** [comment]
Awesome! Thanks for the clarification @garemoko!

No worries. Yeah I agree that's a better process.
