### ISSUE TITLE
Make explicit what value(s) a "Boolean" query string parameter takes

### ISSUE THREAD

**Issue by brianjmiller** [adlnet/xAPI-Spec#536]
For the GET /statements resource the following query parameters indicate they accept a "Boolean":

* related_activities
* related_agents
* attachments
* ascending

Nowhere that I could find do we define what values are expected to indicate true and false when passed on the query string. For the JSON bodies of objects there is a statement that boolean values must be primitives and not strings, but interpretation could be made when it comes to query string parameter values since they are necessarily strings. For the last two of the values the spec says "if true" suggesting that it should be an English word representation, "true" (and by presumption "false"). But systems could decide that any falsey value constitutes "false" and anything else is "true", for instance 0/1. Additionally the table represents the default value as "False" presumably meaning not true as opposed to literally "False", which could theoretically have a corresponding value of "True" (note capital).

I propose we eliminate the possibility of interpretation and specify "Boolean"s on the query string as being "true" and "false".

**Comment by garemoko** [comment]
We generally give defaults in lower case (there are typos though) so +1 to this being 1.0.3

**Comment by andyjohnson** [comment]
Per the 2/4/2015 call - The literal English word true or false, (translate as String true and false) no allowance for True, False, 1, or 0, etc.  which may be considered equivalents in some languages.  No new requirement, just an example for clarification.
