### ISSUE TITLE
Are group members an ordered or un-ordered list?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#537]
Does the group members property represent an ordered or un-ordered list? The spec uses the words "cluster" and "constituent" in relation to the group member property which suggests it's an un-ordered list but it's not explicitly stated that this is the case. 

If it is an un-ordered list, does that mean that the LRS is free to return members in a different order to the order contained in the original statement, or does the LRS need to retain that original order? It seems to me like the LRS shouldn't have to retain the original order.

**Comment by andyjohnson** [comment]
PR #582 knocks this out.

**Comment by garemoko** [comment]
+1 to close
