### ISSUE TITLE
Returning plain text in Concurrency

### ISSUE THREAD

**Issue by brianjmiller** [adlnet/xAPI-Spec#538]
Within the Concurrency section there is the following requirement:

> * MUST return a plain text body explaining that the consumer SHOULD
>   * check the current state of the resource.
>   * set the "If-Match" header with the current ETag to resolve the conflict.

(ref: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#lrs-requirements-5)

Should this be interpreted as "text/plain" or non-binary? In other words is "text/html" considered "plain" or must it be "text/plain" and not anything else equating to non-encoded text?

**Comment by garemoko** [comment]
+1 @fugu13's suggestion

**Comment by garemoko** [comment]
Didn't get to PR this ahead of the call, but it's ready for PR IMHO.

**Comment by andyjohnson** [comment]
Per the 2/4/15 call, check out the PRs.
