### ISSUE TITLE
ISO 8601 timestamps - basic/extended format mixing

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#541]
__The issue__
ISO 8601 defines two formats for date and time representations: Basic format (YYYYMMDDThhmmss±hhmm e.g. 19850412T101530+0400) and Extended format (YYYY-MM-DDThh:mm:ss±hh:mm e.g. 1985-04-12T10:15:30+04:00). The difference between the two is that extended includes dashes and colons whilst basic does not. It's not allowed under ISO 8601 to mix the two formats. 

ISO 8601 is the required format for date and time representations in the Experience API for example for the timestamp and stored properties of the statement. The specification links to a Wikipedia article on ISO 8601: http://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators. Though this article mentions basic and extended format in the introduction, to the unwary the section on timezones may be taken to imply that either format can be used for the timezone designation, regardless of the format used for the rest of the string. This would be an incorrect interpretation as mentioned above. 

PHP contains a function and constant which allows developers to convert a date/time into an ISO 8601 formatted string: http://php.net/manual/en/class.datetime.php. This contains a bug such that it returns an invalid ISO 8601 timestamp where the main timestamp is in extended format but the time zone is in basic format. The bug and a work around are described here: http://php.net/manual/en/class.datetime.php#116085

Any Activity provider using this PHP function and unaware of the bug is likely to be issuing statements with this invalid format. This is not simply an issue for nit-picking spec conformance, but an actual interoperability issue as an invalid format could cause problems for clients handling the data. See for example: http://php.net/manual/en/class.datetime.php#111532 which also provides an alternative workaround for the bug. 

Currently the following LRS behave in the following ways to receiving a statement with a timestamp malformed in this way:
* SCORM Cloud rejects the statement
* Wax accepts the statement but displays it in its UI (and presumably returns it?) with full extended format. 
* Learning Locker accepts the statement and displays it in its UI (and presumably returns it?) with the original incorrect format. 

TinCanPHP appears to use the function in question. https://github.com/RusticiSoftware/TinCanPHP/issues/15

__Proposed Solution__
Whilst I don't think we need to add any new requirements, I do I think it's important that we highlight this issue to PHP developers adopting the spec. Could we add a section titled ````Note on ISO 8601```` that consists of text broadly in time with paragraphs 1 and 3 of my summary of the issue above? 

Another point for consideration is could we allow the LRS to accept incorrectly formatted timestamps  but require that the LRS always returns correctly formatted timestamps? Perhaps this is a rabbit hole we don't want to go down though, as it leads to the situation where content works in one LRS but not another. 

Or should we require the LRS to accept timestamps with this particular quirk? I don't think we should as this issue is a relatively easy fix for PHP using adopters.

**Comment by andyjohnson** [comment]
I believe this can be closed, did we get everything in the PR @garemoko?

**Comment by garemoko** [comment]
Which PR?

This is different to the issue addressed here https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#requirements-8 if that's what you're thinking of.

**Comment by garemoko** [comment]
This should be covered as part of, or after https://github.com/adlnet/xAPI-Spec/issues/592

**Comment by fugu13** [comment]
Re: this one, Wax has started tightening our ISO 8601 validation (we discovered a library we used had loosened theirs), though I'll do a review to make sure we reject strictly this case.

**Comment by andyjohnson** [comment]
Let's make a Conformance Test around this particular case, but the consensus on the 2/18/15 call is to follow current spec language to reject.  Now closing the issue.

**Comment by ryansmith94** [comment]
Can we please reference the part of the spec that says the formats can't be mixed in this issue?

**Comment by ryansmith94** [comment]
http://php.net/manual/en/class.datetime.php#116085 references 8601:2004, 4.3.2 Complete representations

**Comment by garemoko** [comment]
@ryansmith94 this issue is closed so there's a risk your comments get lost. 

We agreed on a call not to change the spec for this and just include a conformance test as it was felt that ISO 8601 was already clear. If you feel strongly against that conclusion, please do open a new issue referencing this one.

**Comment by ryansmith94** [comment]
@garemoko I don't disagree with it and I can see what was agreed. I just wanted a reference to the ISO 8601 spec stating what you'd previously said for future reference.
> It's not allowed under ISO 8601 to mix the two formats.

**Comment by garemoko** [comment]
I'm not sure it's explicit in the ISO spec that timestamps are not mixed but is strongly implied as an assumption by the following:

* It's never explicitly allowed to mix the formats
* All examples throughout are clearly marked as extended or basic format
* In scenarios where mixing could accidentally happen (both relating to duration) it's specifically disallowed:
    * Section 4.4.4.4 requires when joining a duration to a timestamp that both must have the same format, implying an assumption that each have one format or the other. 
    * 4.4.5 is also clear that durations are either basic or extended, not mixed. 

So there's not a specific section to reference, but it is still clearly intended by the ISO8601 authors.
