### ISSUE TITLE
Meta-Issue: Milestones

### ISSUE THREAD

**Issue by canweriotnow** [adlnet/xAPI-Spec#545]
I'd like to request that the repo admins create milestones so that we can tag issues and PR's to planned releases.

Much of what I'd like to see/implement in xAPI is definitely 2.0 material, and I think it would disambiguate posted issues if there was a 2.0 milestone (preferably even with a guesstimated, mutable planned delivery date) to which it could be pinned so that those looking to 1.0.3 issues could ignore them :smile_cat: 

Having more immediate milestones, e.g., 1.0.3, 1.1.0, etc. would also be useful, helping us to sort proposals by their implications for compatibility based on semver.

**Comment by garemoko** [comment]
Let's discuss this on a call sometime soon and get the issue closed either way. 

My view is that the decision should sit largely with @andyjohnson. Will using the milestones feature make Andy's job of managing the repo easier or harder?

**Comment by andyjohnson** [comment]
I'm fine to adjust either way, let's discuss on today's call.

**Comment by andyjohnson** [comment]
Per the 2/18/15 call, will use milestones as needed - some to be implemented early will be "pre-formatting for 1.0.3" , "formatting changes for 1.0.3" and "administrative cleanup for 1.0.3".

**Comment by andyjohnson** [comment]
Milestones for 1.0.3 now created.  Closing issue.
