### ISSUE TITLE
How to avoid other users' data embezzling and statements manipulation

### ISSUE THREAD

**Issue by gianpieropiccolo** [adlnet/xAPI-Spec#548]
Hi All,

according to figure http://cdn4.tincanapi.com/wp-content/uploads/2012/07/learning-data-delivered-to-LRS.png (of the LRS overview http://tincanapi.com/learning-record-store/), it's possibile that the actor's browser directly sends the statements to an LRS. To achieve this, the html page (showed into the end-user's browser)  contains the authority's credentials for authenticating to the LRS. This is a point of care regarding security: an end-user could get the authority's credentials for querying the LRS to embezzle the other users' statements and data. And furthermore, how about manipulation of the statements before sending to the LRS?
An alternative could be that the statements have to be generated by the LMS (in user's shoes) rather than by the end-user's browser. But this will be in opposition to the figure quoted above, to the TinCan_Prototypes and in general to the simplicity of the architecture.

Maybe my worries are caused by my ignorance of the TinCan Architecture.

In every case, any response will help me (and, hope, others) to learn more about TinCan API.

Thank you.
Gianpiero Piccolo

**Comment by garemoko** [comment]
This is a question, not a patch issue and can probably be closed.

**Comment by gianpieropiccolo** [comment]
Sorry! It was the first time I wrote on github :-) I'm closing it. Thanks again.

**Comment by garemoko** [comment]
Thanks! Keep the questions coming! 

My comment was more aimed at @andyjohnson who is used to my directness, but thanks for closing!
