### ISSUE TITLE
LRS returning empty pages of results with a more link.

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#549]
See this thread here: https://github.com/RusticiSoftware/TinCanJS/pull/95

To me, that LRS behaviour seems weird. Am I missing something?

**Comment by garemoko** [comment]
One to discuss on a call sometime soon, ideally with @fugu13 and @brianjmiller present.

**Comment by andyjohnson** [comment]
This can happen as a result of algorithm chosen for querying/retrieval.  Argument for requiring one result is based on "IF there is a result".  Consensus on 2/18/15 is to close the issue - LRSs can differentiate fixing "annoying" behavior.
