### ISSUE TITLE
Clearer language is needed for relative endpoints being required

### ISSUE THREAD

**Issue by fugu13** [adlnet/xAPI-Spec#552]
Right now there's an awkwardly phrased section near the start of https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#70-data-transfer-rest that lays out how parts of the example endpoints are examples, and the other parts are the real relative endpoint values, but it should be stated in terms of LRS MUST somewhere.

**Comment by garemoko** [comment]
PRed this just now. @fugu13 - does this (combined with https://github.com/adlnet/xAPI-Spec/commit/961a5c7cf74d1d1bd1dbdce2202b047965a71303) address your concerns?
