### ISSUE TITLE
Extensions Requirement

### ISSUE THREAD

**Issue by ljwolford** [adlnet/xAPI-Spec#553]
It's a minor point, but currently there is nothing saying there has to be at least one key/value pair in the extensions map. This just leaves it open to someone submitting statements that has extensions : { } which doesn't provide any value, yet doesn't really hurt anything. Should there be a requirement added saying it can't be empty?

**Comment by canweriotnow** [comment]
@garemoko IMHO, saying 2.0.0 is "many years from now" is equivalent to saying "this is vaporware"

**Comment by garemoko** [comment]
This (blanket language about empty properties) should be done as part of or after https://github.com/adlnet/xAPI-Spec/issues/590.

**Comment by andyjohnson** [comment]
Yep, definitely part of the overall re-structure.

**Comment by andyjohnson** [comment]
We've addressed the "empty" issue as a part of the 1.0.3. restructure.
