### ISSUE TITLE
Canonical requirement

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#555]
In determining what an LRS does in the event of getting access to metadata (Section 5.4), we have this text:

"If this metadata is provided as described above, it is the canonical source of information about the identifier it describes."

There is no SHOULD or MUST here, but it seems like a MUST.  However, the canonical tag of the format property seems to give the LRS more leeway:

If "canonical", return Activity Objects populated with the canonical definition of the Activity Objects as determined by the LRS.  

I suggest we clean up this language with either a) a process and expectations for the LRS or b) softening language suggesting the LRS MAY update definitions based on metadata, but canonical itself cannot be counted on across LRSs (which of course, makes me question the value of it in the first place).  

In terms of a conformance testing requirement, here is the issue we're looking at:

For any of the IRIs in 5.4, IF metadata is provided in a way consistent with 5.4, can we have a test that uses the "canonical" format to see if that update is indeed captured?  (This of course assumes correct authorization)

**Comment by garemoko** [comment]
Another candidate issue for a spec call discussion I think.

**Comment by andyjohnson** [comment]
Per the 2/18/15 call.   We need to disambiguate "canonical" away from the IRI concept because there is the "canonical" retrieval.  While these are "the same", Statement activity definitions can be richer.  Procedurally, there is nothing to do "every time".  Recommend also introducing a vocabulary of "Person who coins URI which is used in Statements" as opposed to just Activity Providers", could also have a "Meaning Seeker".  URIs can get stale.  "Strong presumption that what is at the URI is correct and overrides the parts they may receive via Statements."  Open for PRs!

**Comment by garemoko** [comment]
Working on a commit for this now; I'll not PR until the branching issue has been resolved. 

Looks like some progress has already been made since this issue was raised.

**Comment by garemoko** [comment]
Here's the diff: https://github.com/garemoko/xAPI-Spec/compare/issue-555#diff-68cd6732e400b6e64376effdb84b970e

Feel free to comment in this issue or on [this commit](https://github.com/garemoko/xAPI-Spec/commit/12ba2e15789fae63158e04ac245e02663b81c968) until I get the PR up.

**Comment by garemoko** [comment]
Can this be closed now?
