### ISSUE TITLE
Attachments: sha2 vs. fileUrl

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#557]
We seem to have a couple areas that need tightening in attachments.

First, the table indicates that sha2 is required, however, it doesn't seem like it is required in the case of where fileUrl is used and there is no actual attachment.  I think this just may have been an oversight in the table update, where we don't really have a "conditional" required. I propose moving this down as a requirement to the "multipart-mixed" branch below.

It also seems that fileUrl is allowed in a multipart-mixed request ("When receiving a PUT or POST with a document type of "multipart/mixed”, an LRS MUST reject batches of Statements having attachments that neither contain a fileUrl nor match a received attachment part based on their hash."), but we don't have the requirement.  I propose adding:

A Statement within the first part of a multipart/mixed request (per Transmission format), MAY have a fileUrl

This leads to another question, can a Statement have both a sha2 and fileUrl?  It would really make things simpler if this was a straight "no", so consider the following:

1)  the example just above - we'd want to not have an extra sha2
2)  an example with an application/json header that uses sha2 (if there isn't actually an attachment it doesn't break the multipart-mixed requirement) with the intention of relying on the fileUrl
3)  We need to expand the logic of the X-Experience-API-Hash header vs. sha2 in Statements.  These need to be 1:1, checked on both sides, not just a check on each X-Experience-API-Hash header corresponding to a sha2.  This gets really messy if both fileUrl and sha2 are allowed in the same Statement.

**Comment by garemoko** [comment]
Holding of PRing this until https://github.com/adlnet/xAPI-Spec/pull/608 is merged to avoid a possible conflict.

**Comment by garemoko** [comment]
I believe this can now be closed.
