### ISSUE TITLE
Content-Length header requirement

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#565]
From 7.10:

"The Content-Length header MAY be omitted, in order to avoid wasting LRS resources"

This is the first time this header is mentioned.  I suggest we either add more guidance in other places i.e. (in the APIs) or omit this requirement as it is only a MAY.

**Comment by garemoko** [comment]
Proposed fixed:

* Add a list of required headers near the start of 7.0
* As the basis of that list, use the headers given in the 'normal request' example in https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#appendix-g-cross-domain-request-example

These headers are:

    Accept
    Accept-Encoding
    Accept-Language
    Authorization
    Content-Type
    X-Experience-API-Version
    Content-Length

**Comment by garemoko** [comment]
Working on a branch for this now following my proposal. Will PR after repo re-org. 

Please do contest this proposed fix and/or list of headers if you don't agree!

**Comment by garemoko** [comment]
Here's the branch: https://github.com/garemoko/xAPI-Spec/compare/issue-565

This has developed from what I proposed above.

**Comment by garemoko** [comment]
I believe this can now be closed.
