### ISSUE TITLE
tags and branches should have different names

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#568]
There is a tag and a branch labelled "1.0.2". The branch has commits which are much later than the tag. Because the branch and tag have the same name, it's hard to link to code at the point of the commit. 

Am I right that the tag is correct and the branch is wrong? I think it has to be. 

Also: this link (which is in the development 1.0.3 version) compares the 1.0.1 tag to from 1.0.2 branch, not the tag: https://github.com/adlnet/xAPI-Spec/compare/1.0.1...1.0.2

Until we rename the branch (we should) the actual 1.0.2 diff is here: https://github.com/adlnet/xAPI-Spec/compare/1.0.1...a752217060b83a2e15dfab69f8c257cd86a888e6

The spec at the 1.0.2 tag is here: https://github.com/adlnet/xAPI-Spec/tree/a752217060b83a2e15dfab69f8c257cd86a888e6

**Comment by ljwolford** [comment]
Is that branch even still in use? The last use for it was 2 months ago. If it is not being used then it can just be deleted, else if it needs renamed we'll have to make sure anyone using it is aware of the name change so they can update their local repos with the change. Hopefully that'll take care of the comparison links then.

**Comment by garemoko** [comment]
This is on @andyjohnson to fix. I think just delete the branch.

**Comment by garemoko** [comment]
Thinking more on this, most people look at the current master branch of the spec when developing. This is wrong, but it's reality. I propose we create the following branch structure:

1.0.0 - the spec as at 1.0.0
1.0.1 - the spec as at 1.0.1
1.0.2 - the spec as at 1.0.2
master - the spec as at the current published version i.e. 1.0.2
1.0.3 - the development version of the spec. PRs would be made against this branch. To release we'd merge this branch into master. 

This has the added benefit that any links to the spec will always point at the latest release version. 

@andyjohnson if you're happy to temporarily give me collaborator access I can set this up. Any outstanding PRs would need to be recreated, so we'd probably want to get as many as possible merged before doing this.

**Comment by andyjohnson** [comment]
If people are happy with it, @ljwolford can take care of it after we get the PRs nailed down.  None of the current ones seem too controversial, so if we can get some +1s, I think we can even get this done today.

**Comment by RoboSparrow** [comment]
+1

**Comment by andyjohnson** [comment]
Cleaned up!  Closing.
