### ISSUE TITLE
Move section 4.1.3.2

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#572]
Section 4.1.3.2 (https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#4132-use-in-communities-of-practice) should be moved into 5.4 (identifier metadata) and re-worded to apply to all IRIs, not just verbs.

**Comment by andyjohnson** [comment]
Part of 1.0.3 restructure and there is a new issue around all of the IRIs as opposed to just the verbs (#729)
