### ISSUE TITLE
Getting canonical statements changes the statement. 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#573]
Consider the following scenario. 

1. Application A sends a statement to LRS B. 
2. LRS B looks up the activity metadata and builds a definition of the activity that's different to the one in the statement, it's canonical definition. 
3. Application C gets the statement from LRS B, requesting a format of 'canonical' which LRS B duly returns. 
4. Application C forwards the statement including the canonical definition to LRS D (uh-oh!)
5. LRS E queries LRS B and LRS D for statements requesting a format of 'exact'. It receives statements with the same id but different activity definitions. 
6. Application F requests statements from LRS E requesting a format of 'exact'. LRS E doesn't know which definition to provide. 

The problem occurs in step four and clearly it's a bad idea for application C to be forwarding statements using the 'canonical' format. We don't disallow or discourage it though and fixing this issue might be as simple as adding some language to that effect. 

Another (in this case breaking) option is that the LRS tags statements that have been returned in "ids" or "canonical" format so that systems further down the chain know what they're getting.

**Comment by bscSCORM** [comment]
I don't think the scenario you describe is actually a problem for immutability -- it does mean that there is no sure way to get "exact" from a distributed system, only from the specific LRS statements are originally sent to it, but that's a limitation of the "exact" feature, not a problem for "immutability" conceptually.

Consider this text:
`
Aside from (potential or required) assignments of properties during LRS processing ("id", "authority", "stored", "timestamp", "version") Statements are immutable. Note that the content of Activities that are referenced in Statements is not considered part of the Statement itself. So while the Statement is immutable, the Activities referenced by that Statement are not.
`

Found here: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#41-statement-properties

So, statements with different associated activity metadata _are_, by definition, identical as long as they have the same activity IDs, even if that metadata is different. Without this definitions IDs would be substantially less useful, as systems would have to compare all the metadata to determine equivalence, and couldn't blindly categorize all statements referring to the same activity ID together.

I don't see this limitation for 'exact' as worth fixing either -- 'exact' makes sense as a reporting convenience for a single LRS, but it would be unreasonably costly to require LRS-> LRS communication to use exact.

**Comment by garemoko** [comment]
Thinking this through a little more, I guess LRS E could determine the earliest definition by looking at the stored property.

I'll leave this issue open a week or so in case anybody else wants to comment then close.
