### ISSUE TITLE
Consider RFC 3339

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#587]
On the call today somebody who couldn't talk asked if we use RFC 3339. Currently we don't mention this, but maybe we should look at it. 

Anybody got a good reason we should use this? 

https://www.ietf.org/rfc/rfc3339.txt

**Comment by brianjmiller** [comment]
I'm :-1:, but I don't necessarily fully understand what it adds. A cursory look seems like the only thing it brings into play is "-00" as a TZ offset which isn't allowed by ISO8601. It seems to lessen the strictness for *very* little benefit. +1 to needing to hear the benefit.

**Comment by canweriotnow** [comment]
:-1: to anything compromising ISO8601 compliance.

**Comment by garemoko** [comment]
Seems like concensus is no. Closing.
