### ISSUE TITLE
Usage of asterisks in spec

### ISSUE THREAD

**Issue by RoboSparrow** [adlnet/xAPI-Spec#589]
Hi ADL,

Some `properties` and `obligations` (MUST / SHOULD / MAY) int the spec are marked with asterisks. What is the meaning of this marking? I was not able to find an explanation. 

Examples
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#requirements-4
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#person-properties

Cheers,
jb

**Comment by garemoko** [comment]
Asterisks are a new feature being included in version 1.0.3 of the spec which is currently under development. For the most part they are being used with SHOULD only and indicate that this is a particularly strong recommendation and will be made a MUST requirement in a future version, e.g. 1.1.0. 

There's a couple of MAYs marked with asterisks too. This are to flag that they'll be reviewed in 1.1.0 as the SHOULD*s are changed to MUST. It may be that some MAYs are no longer allowed once the SHOULD* becomes a MUST. 

We should update the MUST / SHOULD / MAY definition in the definitions section, so please leave this issue open until thats done.

**Comment by RoboSparrow** [comment]
Thanks for clarifying!
