### ISSUE TITLE
Move section 4.1.12 data Constraints. 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#590]
Section 4.1.12 should be moved to the introduction of a new section 4 which incorporates an introduction, the current section 4 Statements and the contents of the current section 5.

4.1.12 should be reviewed carefully and re-worded to apply to the data structure in general, not just statements. Any statement specific content (which I believe is non-existant, but we need to check) will go back into the statements section which will not be 4.2.1.12 or 4.3.1.12 or something. 

This work is a valuable in itself (see the duplication I'm introducing in https://github.com/adlnet/xAPI-Spec/pull/580, which will need to be reverted), but will also help with the IEEE effort.

**Comment by andyjohnson** [comment]
I'd almost think we'd include the Client requirements as a part of a section that includes things like how to use JSON, no multiplicity and changing of properties, following the tables as requirements, etc.  The LRS requirements should head up the LRS section.

**Comment by andyjohnson** [comment]
This has been addressed as a part of the restructure.
