### ISSUE TITLE
Add a "types" section

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#592]
We need a section where requirements relating to re-used types can live centrally. Something similar to the misc objects section. 

The ones I'm thinking of in particular are:

* UUIDs
* ISO 8601 timestamps
* ISO 8601 durations
* lang codes
* IRIs

We can then link to the relevant sub-section (so it should include anchors) whenever the type is invoked.

**Comment by andyjohnson** [comment]
+1

**Comment by fugu13** [comment]
Makes sense

**Comment by RoboSparrow** [comment]
+1

**Comment by andyjohnson** [comment]
Done as a part of the 1.0.3 Restructure.
