### ISSUE TITLE
Section 6.3: More strictness in ETag definition

### ISSUE THREAD

**Issue by sightworks** [adlnet/xAPI-Spec#595]
I noticed this due to the test suite:

The test suite contains a test which tries:

```
PUT .../activities/state?...
If-Match: <uppercase SHA-1 hash>
```

The problem that I see is that since entity tags are intended to be opaque tokens (according to the HTTP 1.1 spec), if the API's intent is to allow the token to be calculated without being able to read an ETag header, simply specifying that it is the SHA-1 hash of the body leaves ambiguity - the tag value `"B757C..."` is not equal to `"b757c..."`, and it's bound to cause problems with stricter implementations of the HTTP If-Match / If-None-Match semantics.

Propose changing the specified entity tag format such that it is always the lowercased version of the SHA-1 hash, containing only the characters [0-9a-f]; uppercase characters being disallowed.

**Comment by garemoko** [comment]
This is a little above my level of technical understanding, but if I understand this right, I'm +1 to doing this. Not sure what version it would fall into?

**Comment by andyjohnson** [comment]
I'd love to clear up ambiguity if there isn't anything technology-wise that invalidates it.  If it is restricting a previously less restricted data field, I don't see how this isn't a 2.0.

**Comment by bscSCORM** [comment]
We could put in the restriction as a SHOULD*

**Comment by fugu13** [comment]
Agree with restriction here as SHOULD*. Clients should rarely, if ever, use this functionality anyways; always safer to retain ETags returned from the LRS.

Also, we should strike "An LRS responding to a GET request MUST enclose the header in quotes." as that's just duplicating the ETag specification, and potentially confusingly so. We should just say the ETag header must follow RFC 2616.

**Comment by garemoko** [comment]
Skipping this issue for now due to my earlier [comment](https://github.com/adlnet/xAPI-Spec/issues/595#issuecomment-69387279). Will return to it later if nobody else PRs it in the meantime.

**Comment by garemoko** [comment]
* Re-word "An LRS responding to a GET request MUST enclose the header in quotes." to make clear that this is just what RFC 2616 says. 

* New requirement: You should use the etag provided by the server

* New requirement: You should* use lowercase (or maybe uppercase - check what the spec example says and go with that)

**Comment by garemoko** [comment]
@sightworks are you happy to close this?

**Comment by sightworks** [comment]
This looks good to me.

Thanks!
