### ISSUE TITLE
Security of attachments at fileUrl

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#620]
**Question:**
If an attachment file url is used (perhaps without attachment content) can that file url have security restrictions applied to it?

**Example:**
For example, let's say I attach a Google Spreadsheet to an attachment via file url only. Google lets me choose three security settings:

1. Accessible only be certain people identified by a logged in Google account email address. 
2. Accessible only to people in my organisation as identified by Google account.
3. Accessible to everybody.

Are all these valid file urls? 

**My answer:**
My feeling is that because we say that the file url might no longer point to the file, the spirit of the property is that the file might or might not be accessible to the statement recipient at that url, therefore all the above are valid. 

**Proposed change:**
I propose we add some descriptive language outlining that security restrictions around attachments at fileurls are ok, but that the end recipient(s) of the statement needs to be considered, especially if the attachment content is not included with the statement. 

We could possibly also add a MAY requirement for APs. 

I think this is ok for the next patch version because as this was not restricted by the current spec, it's got to be allowed, we'd just be making it explicit.

**Comment by brianjmiller** [comment]
:+1:

**Comment by andyjohnson** [comment]
Per the 3/18/15 call, MAY should be clearer, covers any reason - not just file not found, etc. "accessible" is a good word to cover many cases.  General support for this language being written in.

**Comment by garemoko** [comment]
Apologies I missed yesterdays call. I'm not clear from these comments what changes are envisaged and where. Can anybody comment in [the diff](https://github.com/adlnet/xAPI-Spec/pull/647/files) to make that clear?
