### ISSUE TITLE
Table of Contents Anchor Links

### ISSUE THREAD

**Issue by ty-** [adlnet/xAPI-Spec#622]
The Table of Contents Anchor Links may need review. Section 4.0 links to Appendix B example statement on line 4158 because it's the last anchor to use "#statement". https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#statement

Quick fix would be to switch the ToC anchor to https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#40-statement

or line 4158 can have an explicitly defined anchor "example-statement"

If the spec were to use default anchors rather than ones defined by inside html <a> tags, superfluous HTML can be reduced.  If the spec is widely linked using existing explicitly defined anchor tags, this could be a minor issue.

**Comment by garemoko** [comment]
Thanks @ty- 

Any specific details?

**Comment by ty-** [comment]
Yes sorry, I hit enter too fast, I'm typing something up right now.

**Comment by garemoko** [comment]
I prefer explicit anchors as the numbers on the default anchors can change e.g. if another section is added in.

**Comment by garemoko** [comment]
@ty- is this an issue that you (or somebody else on the ADL team) is planning on running with for a full sweep of the spec?

**Comment by andyjohnson** [comment]
ToC should now be good with 1.0.3 Restructure and TOC update.
