### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#627]
Does an LRS need to support non-latin languages to be conformant? If it doesn't support non-latin languages, is it required to 'not break' and to to return a particular error code? 

Do we need to add this to conformance testing?

**Comment by fugu13** [comment]
I don't know what you mean by "support non-latin languages" exactly, but LRSs are required to support UTF-8 in Statements, which can encode just about any characters you might imagine. Similarly it would be necessary to support UTF-8 in request parameters.

And yes, we should have it in conformance testing; I think there're a few tests related to it already.

**Comment by garemoko** [comment]
Apparently I meant UTF-16 and Brian and Ben made the same comments as you - the LRS MUST reject anything that's not UTF-8, which is pretty clear in the spec (``` All strings MUST be encoded and interpreted as UTF-8. ```) so i'm closing this issue. 

It doesn't look like we have a conformance test for it though; the only occurrence of "utf" is in the markdown, so I'll raise an issue for that on the test suite.
