### ISSUE TITLE
Use of delimiter in correctResponsesPattern array elements

### ISSUE THREAD

**Issue by earleskinner** [adlnet/xAPI-Spec#630]
I was wondering if I could have some clarification about the use of `[,]` delimiter in correctResponsesPattern elements? (under Activity > Activity Definition > Response Patterns)

Example: Choice Interaction Type

My current understanding is:
+ All seperated choices in a single element need to be choosen in order to be correct.
```
// Translates to both golf and tetris need to be choosen.
"correctResponsesPattern": [
    "golf[,]tetris" // and
]
```
+ Only one element in the correctResponsesPattern array needs to be correct.
```
// Translates to both golf and tetris need to be choosen or facebook.
"correctResponsesPattern": [
    "golf[,]tetris", // and
    "facebook" // or
]
```

**Comment by garemoko** [comment]
That's right. See this example from SCORM 2004 4th Ed:

```Example:
• SetValue(“cmi.interactions.0.correct_responses.0.pattern”,“ choice1[,]choice2[,]choice3”)
• SetValue(“cmi.interactions.0.correct_responses.1.pattern”,” choice1[,]choice2”)
This is an example of a choice interaction where the correct responses collection has two patterns. The API method calls indicate that the correct response is either
• “choice1”, “choice2” and “choice3”, or
• “choice1” and “choice2”```

**Comment by garemoko** [comment]
We definitely need to make that clearer in the 1.0.3 development version.

**Comment by earleskinner** [comment]
Thanks, that makes much more sense.

**Comment by garemoko** [comment]
Glad that helps. Please can you reopen the issue so we can make this clearer in the spec?

**Comment by garemoko** [comment]
Another item that comes under #628.

**Comment by andyjohnson** [comment]
Per the 3/15/18 call, still fine with movement away from SCORM language - just clarify the current examples and expand on them.

**Comment by garemoko** [comment]
What specifically is wrong with the examples and how do they need to be expanded? Again, comments in [the diff](https://github.com/adlnet/xAPI-Spec/pull/649/files) most welcome.

**Comment by garemoko** [comment]
Is this resolved now that #649 is merged? I think it can.

**Comment by falcon-git** [comment]
Where does this syntax originate from? Why not use something like
"correctResponsesPattern": [
    {choices: ['golf', 'tetris'], operator: 'and'}
]

or 

"correctResponsesPattern": [
  ['golf', 'tetris'],
  [facebook]
]

**Comment by earleskinner** [comment]
Hi,

It was originally taken from SCORM. There is still an open issue #628 about this topic.

Hope that helps
