### ISSUE TITLE
Agent Profile API

### ISSUE THREAD

**Issue by SundarPPE** [adlnet/xAPI-Spec#631]
Hi,
can I have more clarification on this?
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#combined-information-get
""An LRS capable of returning multiple identifying properties for a Person Object SHOULD require the connecting credentials have increased, explicitly given permissions.""

How to connect the multiple identifying properties for a Person Object?

Thanks.

**Comment by garemoko** [comment]
That's deliberately not specified. The LRS can use any method it likes to link personas. Hopefully it will use some sensible method such as a UI where users can match up their personas (maybe something like [Klout](https://klout.com) or an API that an HR system or LMS can hook into. Some LRS might not have any mechanism for linking personas, in which case the person object will only contain one IFI - the one sent by the client. 

I'll be publishing a [blog](http://tincanapi.com/blog/?utm_source=tincanapi_com&utm_medium=github&utm_term=andrew&utm_content=page&utm_campaign=blog?pmc=em-1) a week on Monday that covers this feature.

**Comment by SundarPPE** [comment]
Thanks for the clarification @garemoko , thats great! :+1:

**Comment by garemoko** [comment]
Does this require any change to the spec or can it be closed?

**Comment by SundarPPE** [comment]
Yes @garemoko that would be nice to add the change in the spec.

**Comment by garemoko** [comment]
**Proposed change:**  add a sentence to the [details section of Combined Information GET](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#details-39). Also tidy up the double "Note that" two sentences in a row in that section.

**Comment by andyjohnson** [comment]
Per the 10/6/15 call, a good place for this is actually in the diagram text of Part 1.  Text would indicate how these agents are connected into a "Person" is beyond the scope of the spec.  It could be done using Statements such as "Agent A is Agent B" to create the Person object or by any other means available.

**Comment by garemoko** [comment]
Note that I've cleared up the double "Note that" sentences in #770. I suggest we address this one as part of the next PR on #749

**Comment by garemoko** [comment]
We should be able to close this now.
