### ISSUE TITLE
What does "when retrieving Statements using explicit or implicit time or sequence based retrieval" actually mean?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#632]
The phrase ```when retrieving Statements using explicit or implicit time or sequence based retrieval ``` is used in relation to returning voiding statements that target statements which themselves meet the requirements of a query filter. 

What does this mean in practical terms? What did we intend it to mean? 

This was added here: https://github.com/adlnet/xAPI-Spec/pull/153 in response to issue https://github.com/adlnet/xAPI-Spec/issues/152

Based on this (and a suggestion from @bscSCORM), I think it means "when not querying for a single statement by statement id or voidedstatementid". 

I think we can word this better.

**Comment by garemoko** [comment]
I'm going round in circles trying to work out the meaning of this requirement. here it is in full:

``` 
The LRS MUST still return any Statements targeting the voided Statement when retrieving Statements using explicit or implicit time or sequence based retrieval, unless they themselves have been voided, as described in the section on filter conditions for StatementRefs. This includes the voiding Statement, which cannot be voided. Reporting tools can identify the presence and statementId of any voided Statements by the target of the voiding Statement.
```

The section it references is (here)[https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#filter-conditions-for-statementrefs]

It seems to be saying "The filter conditions for statement refs section only applies when you query for statements and don't use the since, until or limit parameters (and, by the way) also if you don't use the statementId and voidedStatementId parameters. For voiding statements though, it applies even if you use the since, until or limit parameters; the only queries it doesn't apply to are ones using statementId or voidedStatementId".

Is that right?

What I'd like it to say is: "The filter conditions for statement refs section still applies even if the targeted statement has been voided."

**Comment by garemoko** [comment]
I've made a PR for this based on the second interpretation, which I think it wrong but is the interpretation i like best. Let's discuss!

**Comment by garemoko** [comment]
I've made another attempt, reverting some of the earlier changes following a brief discussion related to this topic with @bscSCORM.

**Comment by andyjohnson** [comment]
Per the 3/18/15 call, worked through how Ben thinks of this and caught the rest of us up - " There are two ways where Statements meet filtering criteria.  The first is when they are normally brought in via normal filters, etc..  In the "OTHER" way, speaking of inclusion criteria beyond the normal querying, the splitting of targeting Statements vs. targeted Statements happens for filters.  The presumption being "If I am interested in "Statement X", then you'd also be interested that someone voided/commented/otheraction "Statement X""

This requirement originated with voiding Statements, but other targeting Statements are also important, just less critical.

We may need to more explicitly define "targeting"

**Comment by andyjohnson** [comment]
and time-based criteria being important on targeting Statements as something may not have changed in the last time period, but could have been targeted (especially voiding)

**Comment by garemoko** [comment]
I've added a definition of 'Targeting Statements'. How's the PR now?

**Comment by fugu13** [comment]
I'm putting a note here that I want to review this, but I ran out of time doing issue review on some of the other stuff; hopefully sometime this week.
