### ISSUE TITLE
At what point does "stored" occur?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#633]
An LRS may take a certain period of time to receive a statement and store it away. Does the stored property relate to the point it received the statement, the point when the statement is fully stored and available for retrieval, or somewhere in the middle? This doesn't seem to be clear in descriptions of the stored property. 

We do say in the Get Statements section: ```...all Statements that have or will have a "stored" property...``` which suggests to me that the stored timestamp is generated before the statement is fully stored, presumably as soon as is practical upon receiving the statement? 

Or maybe it's ambiguous deliberately? In that case we should make it explicitly ambiguous!

**Comment by andyjohnson** [comment]
I like that, "explicitly ambiguous", haha.  Agreed that it is very vague at
the moment.

On Mon, Feb 23, 2015 at 10:41 AM, Andrew Downes <notifications@github.com>
wrote:

> An LRS may take a certain period of time to receive a statement and store
> it away. Does the stored property relate to the point it received the
> statement, the point when the statement is fully stored and available for
> retrieval, or somewhere in the middle? This doesn't seem to be clear in
> descriptions of the stored property.
>
> We do say in the Get Statements section: ...all Statements that have or
> will have a "stored" property... which suggests to me that the stored
> timestamp is generated before the statement is fully stored, presumably as
> soon as is practical upon receiving the statement?
>
> Or maybe it's ambiguous deliberately? In that case we should make it
> explicitly ambiguous!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/633>.
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by brianjmiller** [comment]
I suspect it is any time between when the last statement was stored and when the next one will be stored. So long as the statements are consistently returned in stored order. It might need to relate in some meaningful way to the X-Experience-API-Consistent-Through header but I'm not sure we have explicit linkage of the two right now. I'd expect @fugu13 to have strong opinions on this topic.

**Comment by garemoko** [comment]
I don't think there can be any link to the next statement as the next statement may never come and presumably statements will share identical stored properties e.g. when sent in batches? There's value in the stored property beyond order too e.g. identifying when data was sent (or maybe stopped being sent) for debugging purposes.

**Comment by brianjmiller** [comment]
My point was merely that as long as it is after the time of the last provided Consistent-Through header, and after the last statement seen from a query then it shouldn't matter when the time was derived on the server itself. Once the LRS is considered consistent which assumes a query has occurred (as that is the only way to request whether the LRS is consistent) then the timestamp of the next stored statement has to be advanced, but AFAIK that is the only thing the spec is clear about.

Batches of statements wouldn't necessarily have to have the same stored value, the LRS may be keeping precise enough values that two statements (even in the same batch) rarely would have that.

**Comment by fugu13** [comment]
> after the time of the last provided Consistent-Through header

Yes, definitely. 

> after the last statement seen from a query

Not generally possible once you have a multi server system (if you intend to scale and not have a single point of failure). Conveniently, there's a great article just published going into the difficulty of time agreement: http://queue.acm.org/detail.cfm?id=2745385

> Once the LRS is considered consistent which assumes a query has occurred (as that is the only way to request whether the LRS is consistent)

I'm not quite sure what's intended here, but consistency isn't really a state of the LRS, but a state of a subset of the data in the LRS.

**Comment by brianjmiller** [comment]
@fugu13 right, but from the perspective of the AP they are the same. The non-consistent data doesn't "exist" to them. Which is why the query matters, not because it affects how an LRS would implement the consistent time value itself, but from the outside that is the only thing that can be said about the stored value.

**Comment by fugu13** [comment]
Hmm, maybe an example to illustrate the difference.

Say something queries the LRS. It receives a bunch of statements and a consistent-through time. The Statements fall into two groups before consistent-through, and after. If queried again, there could be statements that had been in the middle of processing that 'appear' in the middle of the after statements.

But the same thing applies to newly sent statements after seeing the query; they could appear in the middle of the after group, and that's all that's required to maintain the contract. Now, from a practical perspective, that's unlikely in many scenarios, but it should be quite easy to trigger intentionally with any multi-webserver LRS.

Any multi-webserver LRS is likely to frequently see clock drift of at least a tenth of a second (yes, even under NTP; the NTP docs mention experiments that found it frequently had the potential to reach a second, not even counting how an NTP daemon can lose brief contact with the server).

So, we have two LRS web servers, W1 and W2, where W2's clock is a hundred milliseconds after W1. It would be easy for a pattern to occur where: statement S1 is sent (and gets routed to W2) and receives stored time T1, query is sent such that it sees S1, statement S2 is sent within the hundred millisecond window after T1 (and gets routed to W1), and receives stored time T2, T2 < T1. When another query occurs, it will see S2 as occurring before S1, and that's fine.

You might argue that then they should coordinate on a database's time, but then you just push the same problem down to the database (and no, database's *don't* generally have a solution, so doing so just adds a needless network roundtrip).

Really, no multi (stored clock) server LRS can report a consistent-through that's based on a delay of less than the probable max clock drift between the servers, which should be considered about one or two seconds.

**Comment by andyjohnson** [comment]
3/18/15 call - defer to discussing online and PR evaluation.

**Comment by garemoko** [comment]
Is this accurate?
```The stored time represents some time between when the LRS receives the request to store the Statement and when the Statement is available for retrieval. ```

What about this?
```The stored time represents some time between when the LRS receives the request to store the Statement and when the LRS responds to the request. ```

Let me try another question too:

If I'm building an LRS, should I make generating the stored time the first thing I do when receiving a statement/batch or the last thing I do before responding to the client? Or does it happen somewhere in between? Or even after I've responded to the client (presumably I have to have done a good bit of statement processing though)?

Side question - do batches of statement have to retain their order in terms of stored time? I'm assuming not as some statements in a batch might take longer to process.

**Comment by andyjohnson** [comment]
Per the 5/6/15 call, what we write would actually be very difficult to do any sort of testing as clients/servers, and even multiple-server LRSs will slightly disagree on time.  "Stored" should be sometime in between when it is received and when it is written to data, don't really care if it is exactly what the computer time is.  Can start saying things about the consistent-through window.  Either description above is fine, not a requirement.  Maybe "short and MUST be less than consistent-through".

**Comment by garemoko** [comment]
From Ben's notes: 'stored will be defined as being anywhere between when the statement is received and actually written to storage, we can’t do much about testing it'

**Comment by garemoko** [comment]
Is "MUST be less than consistent-through" right? Isn't it possible to have a stored time later than the consistent-through timestamp but there's a potential of other statements not yet in the LRS between the two? 

I'm not including that in the PR I'm doing now.
