### ISSUE TITLE
authority requirements

### ISSUE THREAD

**Issue by RoboSparrow** [adlnet/xAPI-Spec#635]
Hi ADL,

see [4.1.9 Authority](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#419-authority)

> The LRS SHOULD overwrite the authority on all stored received Statements, based on the credentials used to send those Statements.

..shouldn't it be either **stored** or **received**? 
I assume that **received** would be correct.

**Comment by garemoko** [comment]
Whilst I can see this might be confusing, I think it's technically correct. The LRS will only overwrite the authority on statements that it has both stored and received.

If it receives but doesn't store the statements, it's rejecting them so won't overwrite the authority. 

In the edge case where the LRS has statements in its store that it didn't receive (maybe the LRS instance is created with some existing statements for demo/testing purposes), then it's under no obligation to overwrite the authority. The expectation is that this happens on incoming statements. 

That said, I'd be happy to not explicitly support that very edge case under the assumption that if you're preloading statements you know what you're doing and will/can bend the rules (at your own risk) anyway.   

For clarity, how about:

``` The LRS SHOULD overwrite the authority on all Statements it receives and stores, based on the credentials used to send those Statements. ```

Or even: 

``` The LRS SHOULD overwrite the authority on all Statements it stores, based on the credentials used to send those Statements. ```

I'm happy that 'stores' as a present tense verb allows the edge case outlined above in a way that 'stored' as an adjective (without modification by 'received') does not.

**Comment by fugu13** [comment]
I like that rephrasing @garemoko

**Comment by RoboSparrow** [comment]
@garemoko Thanks for clarifying. This makes absolutely sense. I think I was was a bit lost in translation.
+1 for rephrasing

**Comment by andyjohnson** [comment]
Yeah the last SHOULD is :+1: in my book, @garemoko

**Comment by garemoko** [comment]
**Consensus summary for PR:** replace ```The LRS SHOULD overwrite the authority on all stored received Statements, based on the credentials used to send those Statements.``` with ```The LRS SHOULD overwrite the authority on all Statements it stores, based on the credentials used to send those Statements.```

**Comment by garemoko** [comment]
I think this can be closed now that #652 is merged.
