### ISSUE TITLE
Should "since" be disallowed if a state or profile id are included?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#636]
Currently it's possible for an activity provider to provide both a state/profile id and a since parameter when GETing Documents. In this case, the since parameter is ignored. 

This isn't explicit, but it's the best way I can read that section and how the LRSs I tested against work.  

IMHO the LRS should reject requests that contain both parameters, but I'm not clear on what spec version that'd go in. How about a SHOULD* NOT aimed at activity providers for 1.0.3?

**Comment by garemoko** [comment]
Let's discuss this on a call before PRing.

**Comment by andyjohnson** [comment]
Per the 4/15/15 call - Make sure that after the restructure that any single document query does not include the" since" parameter (as evidenced in the single document aspects of the spec)

**Comment by andyjohnson** [comment]
Also, the requirement would be that since will not affect the query behavior.  The LRS MUST reject because it is ambiguous and the counter-example of "what if I said it was a multiple document GET?" - justified by multiple areas of unrecognized/not properly used parameters

**Comment by garemoko** [comment]
This looks good to me now. I'm closing.
