### ISSUE TITLE
Define "reporting system"

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#638]
In a few places we introduce the concept of a reporting system. E.g. ```A reporting system SHOULD NOT show voided or voiding Statements by default ```. This could be confusing as most LRS products likely are also reporting systems to some degree. When we mention reporting systems what we mean is "Some system that might be the LRS that's displaying data to the user rather than returning data via the API". We're talking about a different role, which may or may not be the same actual product. 

We should look to clarify our use of the term "reporting system" and standardise similar but different terms if/where we use them. I suggest something similar to what I'm proposing for the metadata provider/consumer roles in this commit: https://github.com/garemoko/xAPI-Spec/commit/12ba2e15789fae63158e04ac245e02663b81c968

**Comment by garemoko** [comment]
Also, there is another class of tool 'debugging tool' (e.g. a statement viewer) which will display data, but which we may not want to be restricted in the same way as a reporting tool. E.g. we *do* actually want these to display voiding statements. (Thanks @bscSCORM for highlighting this one).

**Comment by brianjmiller** [comment]
Is it better to define "reporting system" or just not mention it? I'm not sure the sentence mentioned adds any benefit to the spec at all. What people do with the recorded statements is really up to them, I'd be just as happy removing the sentence completely, particularly since it is a SHOULD NOT for something other than an LRS and only partially for an AP.

**Comment by garemoko** [comment]
I don't disagree with that for this case. A middle ground would be to move this into more descriptive language. 

I'm sure there are other instances were we refer to reporting tools though.

Action for me (or somebody else): look through the spec and list out all instances of the term "reporting tool" or similar so we can have an informed discussion.

**Comment by garemoko** [comment]
Here's the list!

* "Data Transfer methods for the storage and retrieval (but not validation) of these Objects to/from a Learning Record Store. Note that the systems storing or retrieving records need not be Activity Providers. LRSs can communicate with other LRSs, or reporting systems."

* "A reporting system SHOULD NOT show voided or voiding Statements by default."

* "The list of scopes determines the set of permissions that is being requested. For example,an instructor might grant "statements/read" to a reporting tool, but the LRS would still limit that tool to Statements that the instructor could read if querying the LRS with their credentials directly (such as Statements relating to their students)." (note the missing space typo after example!)

* "Note: Revision has no behavioral implications within the scope of xAPI. It is simply stored, so that it is available for reporting tools." (note the spelling of 'behavioural' and weird comma!)

* "Client: - Refers to any entity that might interact with an LRS. A Client can be an Activity Provider, reporting tool, an LMS, or another LRS."

* "Reporting tools wishing to retrieve voided Statements SHOULD request these individually by voidedStatementId."

Seems like there's enough there to make it worth defining.

* "Reporting tools can identify the presence and statementId of any voided Statements by the target of the voiding Statement"
