### ISSUE TITLE
Have the LRS return the last modified date of Documents

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#656]
There are cases were a client retrieving documents might want to know when a Document was last modified, perhaps simply to display this to a user. LRS already have to hold this information in order to support the since parameter for Multiple Document GET, but they don't share this information with the client. 

I wonder if this could be returned in a header of Single and Multiple Document GET requests. Using a header would avoid changing the content returned and avoid breaking clients. Alternatively, we could add a parameter (defaulting to false) to enable clients to request the response as an object/an array of objects containing the document/ids and a last-modified property.

I think this would be a minor (1.1.0) change?

**Comment by brianjmiller** [comment]
At least for the single GET, HTTP already has the Last-Modified header which should be used. Certainly the spec could make that a requirement, I imagine that becomes SHOULD*. I imagine Last-Modified for a multiple GET becomes the most recent of the Last-Modifieds since that is when that resource would have been changed?

**Comment by garemoko** [comment]
I had in mind that the multi-document GET would return an array of last modified values, but maybe that's too complex. I can't think of any use case that requires last modified for multi-document GET that isn't covered by the since parameter anyway. Maybe it's just something to do for single document GET for now - a SHOULD* in 1.0.3.

**Comment by andyjohnson** [comment]
To play devil's advocate, is this really something that needs to be in the spec or a feature that would separate LRS performance? :)

**Comment by garemoko** [comment]
That's a good point. This potentially *could* be handled along with other 'direct reporting' considerations.

That said, this particular functionality might help support multi-LRS setups better, in which case it's not a good fit for that category.
