### ISSUE TITLE
Clarify what is returned when a multiple document GET is issued against the State API

### ISSUE THREAD

**Issue by dacdave** [adlnet/xAPI-Spec#659]
Section 7.4 State API \ Multiple Document GET describes the output from this as, "Fetches ids of all state data for this context ..." I am assuming that the "ids" mentioned here are the stateid values that are a required parameter for PUT, POST, etc.

I recommend stating this more clearly, if I am correct, as "Fetches stateids of all state data for this context ..."

**Comment by garemoko** [comment]
Agree with the problem. 

On the solution, I would also or alternatively edit the ```Array of ids``` text below.

**Comment by garemoko** [comment]
This also applies to agent and activity profile APIs.

**Comment by garemoko** [comment]
Can this be closed now?

**Comment by dacdave** [comment]
+1
