### ISSUE TITLE
Ready to PR list

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#666]
I'm opening the issue so I can keep track of issues which are in my opinion ready to PR in the next batch. These are issues where it's clear what the proposed change is and that are are in scope of the next version of the specification. I will use this list myself to work through and others should feel very free to do likewise. Further, if anybody wants to keep their own list in a comment in this thread, please do!

### section 4
- [x] #695
- [x] #696
- [x] #633

### section 6
- [x] #595
- [x] #668 

### section 7
- [ ] #636
- [ ] #631
- [ ] #690
- [ ] #682

### Attachments
- [ ] #658

### Appendix
- [x] #588

### global/section TBD
- [ ] #622 
- [ ] #592
- [ ] #685 (examples throughout the spec)

**Comment by canweriotnow** [comment]
The Issue of The Beast

**Comment by aaronesilvers** [comment]
Well played.




On Wed, May 27, 2015 at 12:17 PM -0700, "Jason Lewis" <notifications@github.com> wrote:












The Issue of The Beast

**Comment by garemoko** [comment]
@andyjohnson do you want me to hold off doing these until after the re-ordering or do one more batch whilst we discuss the structure Google Doc?

**Comment by andyjohnson** [comment]
Yes, please.

**Comment by garemoko** [comment]
Closing this as all the sections have moved and @andyjohnson posted a list of issues on the forum. I may create a new list if I feel like having the groupings by section would be helpful (and Andy doesn't do that in his list).
