### ISSUE TITLE
LRS behaviour in relation to unknown patch versions unclear. 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#668]
See https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#lrs-requirements-5 (this is also an issue in 1.0.2)

If an LRS receives a request using a higher minor version than it recognises, it MUST reject it, but we're silent on what it should do with higher patch versions. 

IMHO the LRS SHOULD* accept any version starting with "1.0."

I did think the spec already said this, but actually it just calls out "1.0" as a shorthand for "1.0.0":

``` The LRS MUST accept requests with a version header of "1.0" as if the version header was "1.0.0". ```

Or was that intended to read to "1.0.x"?

**Comment by garemoko** [comment]
For context, see this commit: https://github.com/adlnet/xAPI-Spec/commit/60970b5ef6654ef1213d77367bde8e499c78665a

Also note that for the version property of statements, we DO explicitly require the LRS to accept unknown patch versions: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#lrs-requirements-1

This implies to me that this should also be applied to the header as a MUST in 1.0.3 as it seems the only reasonable thing to do in that scenario given the requirement to treat the statement version property in that way.

**Comment by fugu13** [comment]
Definitely an oversight in the text; we didn't fully replicate the requirements we wrote for the version in the statement for the version in the header. I'm fine with SHOULD* or MUST for an added line, and prefer the latter; I think we're covered by the adoption of semantic versioning and careful treatment of the requirement elsewhere.

**Comment by andyjohnson** [comment]
Maybe we should just re-write it generically:  If an LRS receives a version
header with only a minor (x.y) value, it will update it with the value of
the latest patch version (x.y.z).  The original intent was just to catch
those cases where people didn't know the difference between the minor and
unpatched minor versions.

On Wed, Mar 25, 2015 at 1:20 PM, fugu13 <notifications@github.com> wrote:

> Definitely an oversight in the text; we didn't fully replicate the
> requirements we wrote for the version in the statement for the version in
> the header. I'm fine with SHOULD* or MUST for an added line, and prefer the
> latter; I think we're covered by the adoption of semantic versioning and
> careful treatment of the requirement elsewhere.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/668#issuecomment-86129994>.
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by garemoko** [comment]
+1 to genericness. 

I'm wondering if there's a way of combining the requirements for the header and statement property so we don't have to maintain two lists. We should certainly link the two sections with a two-way "see...".

**Comment by andyjohnson** [comment]
Sorry re-reading this I am mixing client and LRS responses....needs to be
wordsmithed

On Wed, Mar 25, 2015 at 1:25 PM, Johnson, Andy <andy.johnson.ctr@adlnet.gov>
wrote:

> Maybe we should just re-write it generically:  If an LRS receives a
> version header with only a minor (x.y) value, it will update it with the
> value of the latest patch version (x.y.z).  The original intent was just to
> catch those cases where people didn't know the difference between the minor
> and unpatched minor versions.
>
> On Wed, Mar 25, 2015 at 1:20 PM, fugu13 <notifications@github.com> wrote:
>
>> Definitely an oversight in the text; we didn't fully replicate the
>> requirements we wrote for the version in the statement for the version in
>> the header. I'm fine with SHOULD* or MUST for an added line, and prefer the
>> latter; I think we're covered by the adoption of semantic versioning and
>> careful treatment of the requirement elsewhere.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/adlnet/xAPI-Spec/issues/668#issuecomment-86129994>.
>>
>
>
>
> --
> Andy Johnson
> ADL Technical Team
> 608-318-0049
>
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by andyjohnson** [comment]
So FROM the LRS, all headers are set to <current version> - this is an
active requirement
We expect the LRS to accept ALL version headers which have the same major
(x) and minor (y) value as the current version of the spec (x.y.z) -
requirement in question re-written (meaning slightly changed as before we
didn't say if 1.0.1 and 1.0.0 should both be accepted, but this could be
inferred from semantic versioning)

On Wed, Mar 25, 2015 at 1:27 PM, Andrew Downes <notifications@github.com>
wrote:

> +1 to genericness.
>
> I'm wondering if there's a way of combining the requirements for the
> header and statement property so we don't have to maintain two lists. We
> should certainly link the two sections with a two-way "see...".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/668#issuecomment-86131882>.
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by garemoko** [comment]
@andyjohnson did you mean to close this?

**Comment by andyjohnson** [comment]
I thought about this after closing late last night, I didn't check the merge carefully then after sleeping on it, realized too that I should really validate.  Beat me to the punch!  Reopening.

**Comment by andyjohnson** [comment]
Interesting things around the suffix (with a dash) that we should investigate as a part of the semantic versioning spec but otherwise 4/15/15 consensus is x.y.z is good.

**Comment by garemoko** [comment]
Looking at this to write the PR, I think using xyz will make it a little confusing. We've already made this generic for patch versions; I think it's ok that we have to update it for minor and majpr versions.

**Comment by andyjohnson** [comment]
I'm fine with what you have in the PR.
