### ISSUE TITLE
Make explicit that the LRS MUST validate signatures

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#672]
@brianjmiller just flagged up this blog post: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

TL;DR of the blog: There are two common security vulnerabilities in JSON web signatures relating to allowing a hacker to specify the algorithm used. 

We don't think this is an issue for our spec because we already say:

```The JWS signature MUST use an algorithm of "RS256","RS384", or "RS512".```

Of course, a hacker might ignore that requirement (that's why they're hackers - they break the rules!). However, we're still covered because:

```The LRS MUST reject requests to store Statements that contain malformed signatures, with HTTP 400.```

and also the general principal that LRSs do validate that clients meet their requirements. 

To be on the safe side:

* [ ] We should add some explicit language requiring the LRS to validate that signature requirements are met. At the same time, it might make things clearer if we split out 'signature requirements', 'LRS requirements' and 'client requirements' and then state that the client MUST follow the signature requirements and the LRS MUST validate them. 

* [ ] Once this language is in (at least as an open PR), we should also raise an issue in relation to conformance testing.

**Comment by fugu13** [comment]
JWS is very complicated; I'd be overall against trying to transclude details of the standard into our spec. Malformed JWS signatures covers any violation of the JWS spec, IMNSHO, and the JWS spec is usable enough (if complicated) that we can expect LRSs to follow it. 

Agreed the conformance tests should cover a number of variations of malformed signatures.

**Comment by bscSCORM** [comment]
@fugu13 note that the concern that prompted this would be a JWS signature that is invalid according to _our_ requirements, but valid JWS. eg: it's valid JWS to use a weaker algorithm than we require, but it's not a valid signature according to our spec, so the LRS should reject such a signature.

**Comment by fugu13** [comment]
Yeah, we definitely need to keep restriction of the signing algorithm, but that's already covered (and not a transclusion of the JWS spec, just a restriction on which parts can be used). We're already covered on this vulnerability since "none" is not on our accepted list.

**Comment by garemoko** [comment]
It's more about making absolutely clear that the LRS *has to* validate that and that it's not just a client requirement. Agree that we are covered; it's just about making it crystal clear.
