### ISSUE TITLE
concerns about filter conditions for statementRefs

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#674]
https://github.com/adlnet/xAPI-Spec/pull/650#discussion_r27600554

**Comment by garemoko** [comment]
delete ```or within the "statement" property of the Context.```

**Comment by garemoko** [comment]
Call April 15th: @fugu13 suggests rather than just removing, explicitly state that context statements are not included and suggest that tools can go and get those if they are interested.

**Comment by toaster33** [comment]
Also, what is consensus in regards to a sub-statement's object being a statementRef?  Should it work similar to a object being a statementRef?

**Comment by garemoko** [comment]
In the development version of the spec, we clarify that substatements are [like statements, but not actually statements](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#substatements). 

Based on that, I think we can say that the special filter conditions do not apply to substatements. We should clarify that along with the clarification about context statement refs. 

The spec is already clear that voiding can't be done via substatement:

```When issuing a Statement that voids another, the Object of that voiding Statement MUST have the "objectType" property set to "StatementRef"```
