### ISSUE TITLE
Duration meaning ambiguity

### ISSUE THREAD

**Issue by jakednoble** [adlnet/xAPI-Spec#675]
This has been touched on before, but I could not find any resolution on the topic. Statement result durations have ambiguous meanings when years and/or months are involved. For example, months may have 31, 30, 29, or 28 days.  When determining whether two durations are equivalent, should an LRS simply string match the duration, allow for conversions from years and months, or behave somewhere in between?
String matching maintains the implied precision associated with a duration, but it might be problematic if 'PT90S' is not considered equivalent to 'PT1M30S'.
This issue came up while working on statement conflict tests for the test suite.

**Comment by fugu13** [comment]
For the purposes of statement equivalence, I'd recommend pure string matching, since it'd be really bizarre to get a statement that's identical in all other ways but differs in how the duration is represented. I'd also note, given the context, that no actual statement conflict check is required -- that's an optional part of the standard. An LRS is allowed to just accept all valid statements, so long as it guarantees that the first version received is the only one ever returned.

**Comment by jakednoble** [comment]
Ok. But with respect to an LRS responding with a 409 vs a 204 when it receives a potentially conflicting statement, should an LRS be allowed to respond with 409 if the original statement result's duration is 'PT90S' and the potentially conflicting statement has a result duration of 'PT1M30S'?

**Comment by fugu13** [comment]
I'd say so, yes. Especially as, very funkily, there aren't always 60 seconds in a minute. For example, the last minute of the 30th of June this year will have 61 seconds (assuming the proposal to abolish leap seconds doesn't get adopted before that happens, I think?).

Think of the 409 code as a courtesy notice that you might want to look at what you're sending, not something supporting a larger edifice (hence why it is optional). Anyone sending a statement that differs in no other way than how the duration is represented isn't doing anything interesting, they're just checking something about the extent of that comparison -- which makes it inherently uninteresting to do such detailed checking.

Note that it would also be defensible to *do* some conversions (even the 60 seconds per minute one) in such a comparison, I just don't see any reason it should be required, and the variance among LRSs is non-harmful. So, we can't put this example in the conformance tests.

**Comment by jakednoble** [comment]
Ok. Thanks for the help. I'll enforce string equivalence for durations.

**Comment by garemoko** [comment]
So I checked and ISO 8601 is very clear that a month can be anywhere from 28 to 31 days and that you can't convert months to days unless you know the period of time that the duration belongs to. In our case, you can only know that if you know from a recipe whether the timestamp refers to the start or end of the duration. 

I don't think its unfeasible that an LRS might decide to store the duration in milliseconds and convert back to ISO 8601 for retrieval leading to variations in serialisation of duration. Statement equivalence is also important for statement signing, so this isn't just about the error codes being returned. I think we need to be clear that:

* The LRS MUST NOT return a different serialisation of any properties except those listed here: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#statement-immutablity-and-exceptions.

* When verifying signed statements, clients MUST NOT use a different serialisation of any properties except those listed here: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#statement-immutablity-and-exceptions.

We could even use duration as an example where if the LRS understood the recipe it would be able to sensibly re-serialise duration, but MUST NOT for the sake of other systems that do not understand the recipe and could not verify the new serialisation matches the old. 

So I'm disagreeing that it's defensible to do some conversions; doing so will cause problems for statement signing and possibly when the statement gets passed onto another LRS.

**Comment by brianjmiller** [comment]
I mostly agree with @garemoko and the deserialization/re-serialization is the primary issue. Statement signing is only a problem when comparing to the retrieved statement for meaning, not computing the signature, as the serialized version is stored as a string as part of the signature.

**Comment by andyjohnson** [comment]
I think the two requirements proposed by @garemoko sum up the serialization issues.  I don't thinking tying down the LRSs error codes is necessary for the very reason that exceptions, even ones you don't think of (ok, @fugu13 did) exist.

**Comment by andyjohnson** [comment]
Consensus on the 4/15/15 call is to go with @garemoko 's two bulleted points as requirements

**Comment by garemoko** [comment]
I believe this can now be closed. @jakednoble - not sure if you're still working with/interested in xAPI? If you are, please check and close!
