### ISSUE TITLE
Incorrect resource results in 400 error?

### ISSUE THREAD

**Issue by bs1180** [adlnet/xAPI-Spec#678]
I'm not sure if this is a test issue or if the spec itself needs clarifying.

I'm testing a simple LRS implementation and found a conformance test that expects a [HTTP 400 error for a non-existent endpoint](https://github.com/adlnet/xAPI_LRS_Test/blob/master/src/features/about.feature#L38). I suppose this reflects the requirement under section 7: 
> The LRS MUST reject with HTTP 400 Bad Request status any request to any of *these* APIs that use any parameters which the LRS does not recognize in their intended context in this specification

My initial reaction was that a 404 might be more appropriate, but on further reflection I think the test itself might be overreaching. The test is looking for something outside "these" APIs by checking for a different resource ("/abouts") which is not part of the xAPI spec. I don't think the spec - or the tests - should be concerned with other resources alongside the base endpoint, but perhaps this is something I've overlooked. Is the base endpoint forbidden from having other endpoints outside those listed in [Appendix F](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#appendix-f-table-of-all-endpoints)?

For example, if my base endpoint is just example.com:
example.com/statements - xAPI endpoint so should be tested
example.com/about - xAPI endpoint so should be tested
example.com/foo - outside the spec so shouldn't be tested

Grateful for some clarification!

**Comment by brianjmiller** [comment]
See #601, and https://github.com/adlnet/xAPI_LRS_Test/issues/14.

**Comment by bs1180** [comment]
Thanks very much Brian, I'll add a comment to the specific issue and close this.
