### ISSUE TITLE
Add logos to 1.0.3 branch

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#679]
Currently they only exist in master.

**Comment by brianjmiller** [comment]
When 1.0.3 gets merged to master this will get fixed automatically. Adding them to 1.0.3 too would potentially cause a conflict during the merge.

**Comment by andyjohnson** [comment]
Yeah, I think we don't need to get these in 1.0.3 until the formal
release.  With master being the default branch, people should be able to
find the graphics easy enough.

On Thu, Apr 9, 2015 at 8:50 AM, Brian J. Miller <notifications@github.com>
wrote:

> When 1.0.3 gets merged to master this will get fixed automatically. Adding
> them to 1.0.3 too would potentially cause a conflict during the merge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/679#issuecomment-91220949>.
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by garemoko** [comment]
So we just need to be sure we fork from master not 1.0.3 for the next development version. Tag as a meta issue and leave open as a reminder? Or just close...

**Comment by andyjohnson** [comment]
I think we can just close this, we'll remember to include all files per release :)
