### ISSUE TITLE
Agent Profile API (get agents)

### ISSUE THREAD

**Issue by toaster33** [adlnet/xAPI-Spec#680]
Question regarding ../agents endpoint [(link)](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#agentprofapi): "The Agent Profile API also includes a method to retrieve a special Object with combined information about an Agent derived from an outside service, such as a directory service."

Says combined information and curious if this is Agent from Document Storage or Agent from Statements.  Outside service seems clear.

**Comment by brianjmiller** [comment]
I'm not sure I follow the question, does Andrew's post here http://tincanapi.com/2015/03/02/deep-dive-agent-profile/ help clear things up?

**Comment by garemoko** [comment]
I think I follow the question and that blog should definitely help. 

Short answer: agents represent personas, so @mrdownes on twitter and @garemoko on Github are different personas of the same person. But maybe the LRS has some outside way of knowing that they are the same person - the combined information is information about all the personas. 

There's currently an open PR to make this section clearer. Please feel free to review it: https://github.com/adlnet/xAPI-Spec/pull/669

**Comment by toaster33** [comment]
Thanks, I think that clears it up.  /agents endpoint should return actor within LRS and combines that information with another system if available.  Assuming this does not apply to identified groups in agents.

**Comment by garemoko** [comment]
Yes, I think that's right. There was a time when groups were considered a special type of group but that got removed from the spec. The Agent Profile API only applies to Agents. 

This isn't amazingly clear though, so I'll raise a separate issue for that.

**Comment by andyjohnson** [comment]
This has effectively been moved into #682, closing
