### ISSUE TITLE
Can 'agent' parameter of Agent Profile API contain an identified group?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#682]
See this discussion: https://github.com/adlnet/xAPI-Spec/issues/680#issuecomment-92374857

My answer was no.

**Comment by toaster33** [comment]
Why not?

**Comment by andyjohnson** [comment]
The 7.3.3 already has all the provisions for it, and it is "agent" parameter as opposed to "actor" so I think identified groups are okay.  Would be a 1.1 issue and unless it is terribly difficult for an LRS to implement (which doesn't seem so), I'd say keep it.

**Comment by garemoko** [comment]
So there's two (and a half) questions here:
1. What does the spec require/allow now?
2. What should the spec require/allow in some future version? 
2b. What version?

To clarify my position, I was addressing question 1 - I think the spec currently *does not* allow group objects to be passed to the Agent Profile API instead of agent objects. 

On question 2 - I think we should allow identified groups to be used with the Agent Profile API. "person" is a weird name for an object representing the LRS canonical record for the group (I guess including all members the LRS knows about) but certainly a reasonable use case. 

2b. 'minor' seems reasonable at least until we work out the details. 

@andyjohnson 7.3.3 is the Statement API (at least in 1.0.3, it doesn't exist in master) whereas this issue is about the Agent Profile API. Or am I misunderstanding?

**Comment by dacdave** [comment]
My comment on question #1:

I see nowhere in the spec where we define how an LRS should collect the information and build this special person object that is available from the "agents" endpoint. However, given that section 7.6, subparagraph "Combined Information GET / Details" states that, "The Person Object is very similar to an Agent Object..." and that an Agent is a type of Actor separate from a Group, I agree with Andrew that groups should not be allowed as the returned value from a GET call to this endpoint.

I am open to changing this in the next version of the spec.

**Comment by garemoko** [comment]
@dacdave  the discussion is whether or not a group can be used in the parameter sent to the LRS, not what is received. The LRS returns a person object, not a group or agent.

**Comment by dacdave** [comment]
OK, sorry for muddying the waters.

With my new-found understanding of this issue. I have to +1 Andrew's position that the spec currently spells out that the parameter to the "agents" endpoint GET be an Agent, which is one of the possible values of an Actor and precludes passing a Group as the parameter.

**Comment by andyjohnson** [comment]
My comment was made with some haste as I can't even figure out what I meant by 7.3.3 (maybe section 7.3 table 3?) and mixed up "actor" and "agent".  Yes, the current spec allows only agents, else it would have said actors.  I do see this being able to be expanded, but we'll need some extra discussion on what parts of the group would be returned and potentially even which operations are allowed..e.g.  how does a DELETE of a Group profile work?

**Comment by fugu13** [comment]
Yes, it is restricted to an Agent (as stated).

I recommend that when an app wants to store a profile for an identified Group, it use an Agent with the same IFI (we could even make that a SHOULD, though it should not be a SHOULDstar).

**Comment by andyjohnson** [comment]
5/6/15 - There is wiggle room in regards to the Person, but not the Agent.  Person will be decoupled.  Mostly leave it the same - that if you want to talk about Identified Groups, you can use the same IFI as the Agent.  Could make it a SHOULD (best practice only).  Text in spec is pretty good.

**Comment by garemoko** [comment]
Fixed in a PR
