### ISSUE TITLE
Contributing Doc Updates

### ISSUE THREAD

**Issue by brianjmiller** [adlnet/xAPI-Spec#683]
Minimally the README.md in the root of the repo should be updated to tell users to PR against the "current development branch" and we might even include what branch that is since it doesn't have the same version restrictions as the specification itself.

Alternatively we could move most of what is in the README into a CONTRIBUTING.md file so that GitHub automatically displays a message of how to do so. See https://github.com/blog/1184-contributing-guidelines. The instructions should also be reviewed for continued accuracy, and we might even include a "simple start" section that describes how to PR using GitHub directly since they have online editing capability now.

**Comment by garemoko** [comment]
+1

Assuming this particular change would be made to the master branch.

**Comment by andyjohnson** [comment]
+1

**Comment by garemoko** [comment]
@brianjmiller is this ready to close or still in need of work?
