### ISSUE TITLE
Example statements should include contextActivities category 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#685]
We need to encourage people to use recipes defined by CoPs and certainly should not be encouraging people not to. We should check the example statements to see if their content would be covered by an existing or under development recipe e.g. meetings will be covered by the attendance recipe that TES are working on. 

I expect this next point may be controversial, emotionally fraught and/or full of drama, but it's a really important discussion to agree, so I need to make it: the activity type used for recipes should be ```http://id.tincanapi.com/activitytype/recipe``` as that's an existing IRI in use for this purpose for quite some time.

**Comment by andyjohnson** [comment]
I think the spec document should only go so far as to talk about the existence of CoPs and to follow best practices as they proscribe.  Just as originally things like "verb definitions" were out of scope of the spec, so too are "recipes" or other potentially coined phrases for describing the finer details of how implementations are done within CoPs.  Where I could see some flexibility is in describing types of information one could potentially see at IRIs coined by CoPs.

**Comment by andyjohnson** [comment]
Per the 5/6/15 call - Can do a filled-out cmi5 example.  Could look at taking full Statements out, keeping just parts, citing that there are Statements in the wild.  A little out of scope for defining activity types in the spec.

**Comment by garemoko** [comment]
Love the idea of using cmi5.

**Comment by garemoko** [comment]
I suggest that somebody more closely involved in cmi5 than I does the PR for this.

**Comment by andyjohnson** [comment]
I'll grab this one
