### ISSUE TITLE
Update contributors list

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#693]
10 new people have directly contributed to xAPI.md version 1.0.3 (35 contributors) since 1.0.2 (25 contributors) . Many more have indirectly contributed. 

We should make sure that at a minimum the direct contributors are credited.

**Comment by andyjohnson** [comment]
Absolutely - Please use this issue as a catch-all for people who are to be credited.  For those not already in the contributors list or wishing to modify their entry, please reply with how you would like it represented.  If you DO NOT want to be credited, please also say so here.

**Comment by garemoko** [comment]
I need to move from "Rustici Software" to "Watershed" for this version.
