### ISSUE TITLE
Misleading example: ContextActivities

### ISSUE THREAD

**Issue by earleskinner** [adlnet/xAPI-Spec#694]
Just wanted to bring this to someone's attention:

From: Section 4.1.6.2 ContextActivities Property

Other: **a context Activity** that doesn't fit one of the other fields. For example: Anna studies a textbook for a biology exam. The Statement's Activity refers to the textbook, and the exam is a context Activity of type "other".

* The LRS MUST **return single Activity Objects as an array of length one** containing the same Activity.
* The Client SHOULD ensure that every value in the contextActivities Object is an array of Activity Objects instead of a single Activity Object.

Appendix A: Example statements
This example should really only display one item.

```
"other": [
                {
                    "id": "http://www.example.com/meetings/occurances/34257",
                    "objectType": "Activity"
                },
                {
                    "id": "http://www.example.com/meetings/occurances/3425567",
                    "objectType": "Activity"
                }
            ]
```

A related question:

If ```parent, category grouping & other``` properties in ContextActivities should each supply a single Activity object, why ask for it to wrapped in an array?

**Comment by fugu13** [comment]
Hi Earle,

The requirement isn't that the context activity keys must each have a single-valued array, the requirement is that if a Statement is received where the value is not an array, but a single Activity object, the LRS must return it as a single-valued array (wrapping the original object).

If, on the other hand, the value is sent as an array, then the LRS just keeps it as an array of whatever length it has.

The reason for the requirement is to make it so clients retrieving from an LRS don't have to special-case bare activity objects. The reason we allowed bare activity objects at all is so 0.95 statements (arrays weren't allowed then) remain legal 1.0.x statements, basically, reducing the difficulty for Activity Providers transitioning from 0.95 to 1.0.x.

Sincerely,
Russell Duhon
CTO, Saltbox
Makers of WaxLRS

**Comment by earleskinner** [comment]
Hi Russell

Thanks very much for the explanation.
