### ISSUE TITLE
case sensitivity of email addresses

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#695]
The domain portion of emails is case insensitive. Could this case problems for the mbox_sha1sum property?

Also, the 'Statement Immutability and Exceptions' outlines a number exceptions to immutability. Email address domain case should be on that list. (Also the 'Statement Immutablity and Exceptions' section is missing an 'i' in 'Immutablity.')

Note: this only relates to the domain e.g. ```foo@doMaIn``` == ```foo@domain```

See http://stackoverflow.com/a/9808332/4214694

**Comment by garemoko** [comment]
I suspect the solution here is to require (SHOULD*) mbox_sha1sum to be a sha1 of the email address with a lowercase domain.

**Comment by fugu13** [comment]
I'm fine with SHOULD*-ing. Implementers of mbox_sha1sum should've been aware of this already, as it is a well known issue with emails, but never hurts to advise. Not really enforceable, of course, which is why it isn't too big a deal we haven't had that in the standard.

**Comment by andyjohnson** [comment]
Per the 5/6/15 call, LRSs need to be careful with this.  If they start compareTo on URIs, at that point, they need full suite of URI comparison objects.  Clients SHOULD use lower case (can't be tested for SHOULD*).  MUST would also wreck LRS to LRS and pre-existing domains with caps.
