### ISSUE TITLE
master and latest point release (1.0.2) should be equal but aren't

### ISSUE THREAD

**Issue by ty-** [adlnet/xAPI-Spec#699]
It seems there were 7 commits made to master after the 1.0.2 release.

https://github.com/adlnet/xAPI-Spec/compare/1.0.2...master

Assuming master is equal to the latest point release, is this a policy moving forward from the next point release (1.0.3), or should these changes be merged back into 1.0.2 and re-released?

@garemoko can you weigh in on this?

**Comment by garemoko** [comment]
All of these commits are not to the spec itself but to ancillary files such as the logo image and readme. They don't form part of the formal release, they're just additional files. All spec changes are being made in the 1.0.3 branch.

**Comment by garemoko** [comment]
@ty- are you happy with my answer? Can this be closed?
