### ISSUE TITLE
Get Statements API Full Example

### ISSUE THREAD

**Issue by earleskinner** [adlnet/xAPI-Spec#704]
I'm looking for an example of a real GET Statements API url, because I can't see how on earth I'm meant to add an agent/group JSON object to the request QueryString. I'm also hoping that the xAPI specification is not expecting me to send data as part of the request body.

All the other properties in <a href="https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#723-getstatements">Get Statements</a> are achievable.

**Comment by fugu13** [comment]
Hi Earl,

To query with an agent, take any legal JSON representation of the agent, then encode that representation as a URL parameter (just like any other string) and send it as the agent parameter. Matching is only done on the basis of IFI (mbox, mbox_sha1sum, account, or openid), not anything else in the agent.

As an example, if you wanted to query for the agent with a JSON representation of `{"mbox": "me@example.org"}` you'd encode that to `%7B%22mbox%22%3A%20%22me%40example.org%22%7D`, and then insert it as the agent parameter to get a url such as `https://mysite.waxlrs.com/TCAPI/statements?agent=%7B%22mbox%22%3A%20%22me%40example.org%22%7D`

Something that might be useful: you can't query with a group, but an agent in the agent query parameter will match a statement with a group if it matches either a member of the group's IFI, or an identified group's IFI, as described in the section you linked.

**Comment by earleskinner** [comment]
Thanks very much, this is really useful information

**Comment by fuzzy76** [comment]
Does anyone have an example of an account object?

**Comment by fuzzy76** [comment]
NVM, this did the trick:
```
http://lrs.local/data/xAPI/statements?agent={"account":{"homePage":"http://account.local","name":"122"}}
```

**Comment by Olfa-MESSAOUD** [comment]
Hello,

I want to get the list of all the agents from xAPI statements using the GET request. How should I proceed ? 

Thank you in advance.
