### ISSUE TITLE
Should the LRS reject statements with response patterns containing characterstring parameters of incorrect case?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#712]
Imagine the LRS receives a statement containing something like this (note the capital M):
```
"correctResponsesPattern": [
        "{case_Matters=false}{lang=en}To store and provide access to learning experiences."
    ]
```

Does the LRS accept or reject the statement?

It could be argued that the case requirement [here](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#lrs-requirements-3) applies:

```The LRS MUST reject Statements ... where the case of a value restricted to enumerated values does not match an enumerated value given in this specification exactly.```

In that case the LRS MUST reject the statement. However, this requirement does not explicitly state that it applies to parts of values; correctResponsesPattern is not restricted to enumerated values so this requirement technically does not apply. 

My position, therefore is that the LRS does not reject the statement. In this case, the statement says the correct response is the complete string "{case_Matters=false}{lang=en}To store and provide access to learning experiences."

IMHO we shouldn't change this behaviour, but should clarify in the Characterstring parameters section that the LRS will not reject invalid case but will instead treat the characterstrings as part of the response. I.e. activity providers, you'd better make sure you get it right! The reason is that this is adding another level of validation requirements onto the LRS for a feature that I don't expect to be well used. I don't want to make the validation optional to avoid the statement being accepted in one place and rejected elsewhere. 

Any agreement/disagreement about either my interpretation of the spec today and my assertion that this required behaviour should not change?

**Comment by garemoko** [comment]
Looking at SCORM 2004 4th ed. in relation to whitespace in character strings, it's clear SCORM followed (or was supposed to follow) the approach I'm suggesting of not rejecting the value but treating it as part of the string. 

<blockquote>The name token must be represented as-is (i.e., one of the following: lang, case_matters or order_matters). Any derivatives of these tokens (e.g., padding the token names with white space) will result in an unrecognized delimiter and the set of characters will be treated as part of the underlying characterstring.</blockquote>

and 

<blockquote>SetValue(“cmi.comments_from_learner.0.comment”, ”{lang =fr}Characterstring in the English language”)
There is no delimiter qualifying this Characterstring – “{lang =fr}” is not considered a language delimiter because it contains white space, which is not lexically equivalent to the lang reserved delimiter. In this case, the overall Characterstring includes {lang =fr} and is still considered valid; its default language is English (“en”). If this SetValue call is invoked, the LMS shall set the data model element associated with the call to
”{lang =fr}Characterstring in the English language”, set the error code to 0 – No Error and return true.</blockquote>

**Comment by andyjohnson** [comment]
If you look back to 1.0.2, none of the parameter language was in the spec, so adding anything is a breaking change (and as @garemoko pointed out, a somewhat weak argument for inclusion in a past requirement).  All that was in the spec in 1.0.2 was a bit of guidance saying the interactions consisted of strings and interaction objects.  I think that is all of the responsibility we can reasonably put on the LRS - enforcing the data types.  I agree that the AP better get them right if they are using them!

**Comment by fugu13** [comment]
Agree with @garemoko we should not validate on the LRS. I'd weaken the clarification, though, because the inner workings of the correctResponsesPattern are outside of the LRS's demesne. I do think noting that formatting mistakes may result in parts intended to be delimiters instead being not used as delimiters. Honestly, I half think we should recommend people don't use those delimited options (even if they seem sensible), because systems that (are forced to!) silently absorb errors they could easily catch are very hard to work with. By not using those delimited aspects, life will become easier.

**Comment by andyjohnson** [comment]
Per the 10/6/2015 call, have a sentence that it cannot be rejected for case.  Still working through this, the options are:  1)  recommend not using the delimiters, but being aware they could be a part of the response (i.e. from legacy imported content) or 2) recommend use of the delimiters, but understanding the LRS will not validate them.

**Comment by fugu13** [comment]
What about recommending that, unless you're emulating/porting SCORM communication, you shouldn't use it?

**Comment by garemoko** [comment]
Perhaps. We could also recommend people use an extension if they need to communicate whether or not case matters outside of SCORM style stuff. 

Are we better off recommending not using correct response pattern at all unless you're emulating/porting SCORM communication?

**Comment by garemoko** [comment]
As we're going to discuss this on the call, my proposal is that we add a new second paragraph to the [Characterstring parameters](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#characterstring-parameters) section. 

"Characterstring parameters are not validated by the LRS. Systems interpreting statement data can use their best judgement in interpreting (or ignoring) invalid characterstring parameters and values."

**Comment by andyjohnson** [comment]
Per the 10/21/15 call, the language immediately above is good!
