### ISSUE TITLE
Move Part1 Section 4 into Part 2 Section 1?

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#723]
The JSON formatting makes more sense under xAPI Data (Part 2)

**Comment by garemoko** [comment]
I've got a feeling I suggested this in a PR, but +1 anyway. If I said it originally, I agree with myself, else I agree with whoever did.

**Comment by andyjohnson** [comment]
I think you suggested this in a PR and it was then confirmed on the call, sorry for the brevity above!  This is more of a TODO than a discussion.

**Comment by andyjohnson** [comment]
The restructuring is completed.  Closing.
