### ISSUE TITLE
Client-side X.509 certificate auth

### ISSUE THREAD

**Issue by canweriotnow** [adlnet/xAPI-Spec#725]
Section [6.4 Security](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#64-security) provides for HTTP Basic Authentication and OAuth 1.0 (not sure why it doesn't say 1.0a, but that's another matter).

I've had several conversations recently with CTO's of companies that exclusively do government contracting, and it's been pointed out that in many departments, the _only_ approved authentication mechanism is the use of client-side certificates. Implementing X.509 certs as an auth mechanism is relatively trivial on the server side; the relatively limited use of this auth mechanism is due to the difficulty for the user, but this is nullified when required and managed by the IT department rather than a typical end-user.

I'd be happy to write the PR for this, as it should be a patch-level issue (no breaking backwards-compatibility), and can be added as a MAY or SHOULD (probably the former, for now).

Just wanted to enter as an issue first to get feedback before I start the PR.

**Comment by fugu13** [comment]
There's no need to modify the spec, the auth options in it aren't restrictive. You can have any additional auth alternatives you want without violating the xAPI spec.

Re: OAuth version, OAuth 1.0 as defined by RFC 5849 supercedes 1.0a, as you can see at the top of the 1.0a spec: http://oauth.net/core/1.0a/

**Comment by garemoko** [comment]
If you did add this to the spec, would it include anything about how to implement X.509 certs, or just a note to say that you can? If it's the later then +1 to what @fugu13 said.

**Comment by canweriotnow** [comment]
@fugu13 That's great, I must have read it as more limiting than it actually is. Closing.
