### ISSUE TITLE
Rename § 6.4

### ISSUE THREAD

**Issue by canweriotnow** [adlnet/xAPI-Spec#726]
Apropos of @andyjohnson's [comment](https://github.com/adlnet/xAPI-Spec/pull/707#discussion_r33710520) in #707 (my follow-up [here](https://github.com/adlnet/xAPI-Spec/pull/707#discussion_r35506444)), and following indirectly from #725:

As it's been made explicitly clear on several occasions that infosec concerns are more or less orthogonal to the xAPI spec itself, I propose that § [6.4 Security](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#64-security) be renamed to "6.4 Authentication" or _maybe_ authorization (but that's a stretch), as it really only describes mechanisms of client authentication and really has little to do with security _qua_ security; at the very least, the title might mislead naïve readers to assume that the provisions in 6.4 provide security guarantees, which is at best laughable and at worst downright dangerous. 

In addition to disambiguating the intent and capabilities of the provisions in §6.4 by renaming it, I think it would be prudent to explicitly state in the same section that xAPI does _not_ directly address security, and implementors should follow industry best practices to achieve the level of security they require.

Again, I'd be happy to write the PR, posting issue for feedback.

**Comment by garemoko** [comment]
+1 to the general direction of this. I suggest this is done as part of the restructuring work, in which case @canweroitnow should look [here](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#40-security) and also [here](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#part-three-data-processing-validation-and-security) (I think the part 3 heading has been discussed elsewhere already but not sure where). 

I'm tempted to say "authentication and authorization" but probably just "authentication" is best. Note that the OAuth section currently uses both terms; I didn't check if it uses them distinctively. 

Looking forward to the PR!

**Comment by canweriotnow** [comment]
Thanks, @garemoko, I'll review those sections as well. I also agree that just "authentication" is best since although OAuth provides for "authroization scopes", it doesn't actually manage authorization itself. 

I'll come back with a PR soon :smile_cat:

**Comment by andyjohnson** [comment]
I'm definitely on board with this as I don't think our intention is to take on all of the security problems of the world within this spec.

**Comment by fugu13** [comment]
Something like this sounds good

**Comment by andyjohnson** [comment]
Per the 10/6/15 call, okay moving to "Authentication" instead of "Security".

**Comment by canweriotnow** [comment]
Sorry I haven't had time to move on this, but I found another aporia I'd like to resolve... the term "Application" is used consistently in §6.4 and I _assume_ it has the same referent as "Activity Provider," but I suppose I could be wrong... are we also talking about... "Activity Consumers", e.g. external reporting tools that use xAPI as transport to get their data? 

I thin that, at a minimum, the definition section and/or the Authentication section need to provide some disambiguation as it seems "Application" is introduced here for the first time(?)

I'll try to get back on the PR for this (and hopefully back on the calls!) but I'd like some input on this issue as I draft the PR.

**Comment by garemoko** [comment]
So in the restructure branch that;s [part 3, section 4](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#security). This isn't restricted to Activity Providers, but any application that authenticates with the LRS, including other LRSs. We use the term "Client" elsewhere for this broad category - agree that we should be consistent.

**Comment by andyjohnson** [comment]
Good catch.  Also agree with "Client".

**Comment by garemoko** [comment]
On "Activity Consumer" - I'd read that as a weird jargon term for "learner". I don't think we should use that term.

**Comment by garemoko** [comment]
![image](https://cloud.githubusercontent.com/assets/1363163/10646712/9813ad7a-782c-11e5-9bb8-d9a46b417694.png)

**Comment by garemoko** [comment]
![image](https://cloud.githubusercontent.com/assets/1363163/10647009/07f436ae-782e-11e5-85b2-7956eca28336.png)

**Comment by andyjohnson** [comment]
Per the 10/21/15 call, we are all good with Clients, LRS, and Activity Providers.  Discussion on the largest "container" being Ecosystem, with the generic name under that could be System, Service (used at multiple levels), or Application.  Consistency is the key.

**Comment by garemoko** [comment]
Other more minor types of thing: metadata provider and metadata consumer

**Comment by garemoko** [comment]
This issue has gone way off topic. The original issue is now fixed and the side topic is now covered in https://github.com/adlnet/xAPI-Spec/issues/832. 

Propose we close this.
