### ISSUE TITLE
Example 'simplest possible statement' is not as simple as possible

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#727]
Take a look at the example statement under the introduction:

```An example of the simplest possible Statement using all properties that MUST or SHOULD be used:```

This statement includes an id and verb display which aren't required if the statement is being sent to the LRS and is missing timestamp, stored and authority properties that need to be included when returned from the LRS. It's missing a few properties that I'd generally expect "good" statements to include, but I think recommended optional properties is really too contextual to set out in the spec. 

I propose:

* Remove id and verb.display properties from the example statement
* Re-word the introduction to  ```Below is an example of the simplest possible Statement using all properties that MUST be included in a Statement sent to an LRS. It is recommended to also populate optional properties as they are relevant. When this Statement is returned from the LRS it will include some additional properties added by the LRS.```

**Comment by fugu13** [comment]
Pregenerating id and timestamp should be very strongly encouraged (only way to guarantee idempotency of statement sends), so maybe, instead of "simplest possible Statement" go with "a very simple Statement" and then explain we've included all the required properties, plus we've included those two properties because it is an extremely good idea to include them in even simple statements?

**Comment by garemoko** [comment]
Looking at this again, I can see that this example has followed the 'Required' column of the tables (aside from the 'en-US', but it doesn't make sense to have a display property without any languages). 

On that basis, maybe we leave the example as is and just add ```It is recommended to also populate optional properties as they are relevant. When this Statement is returned from the LRS it will include some additional properties added by the LRS.```

On timestamp, this is currently listed as 'optional' rather than 'recommended'. I agree with this because although I'd recommend timestamp in most cases, in the situation where the AP doesn't have an accurate timestamp (maybe it doesn't know it's timezone) then it's not recommended. 

I do think we should make sure the examples ion appendix A all have timestamps and ids though.

**Comment by andyjohnson** [comment]
Per the 10/21/15 - Will augment with a simple Statement with the subtext describing inclusion of optional properties and inclusion of properties when the Statement is returned.
