### ISSUE TITLE
Look for "past tense" in Document to clarify

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#730]
We want to drive home the point that IRIs don't have tense, and instead want  to focus on the human readable parts i.e. display, and IRI fragments.  This needs to be done uniformally in the spec.

**Comment by garemoko** [comment]
Searched the document for "past tense" and there's two hits:

"Statements are information about a tracked learning experience. Typically, the information represented in the Statement has already happened. Thus, the natural language used in "display" or in the human-readable portion of the verb id will usually use the past tense." - 2.3 Statement Lifecyle

"The display property has some flexibility in tense. While the Verb IRIs are expected to remain in the past tense, if conjugating verbs to another tense (using the same Verb) within the Activity makes sense, it is allowed." - 2.4.3.1 Use in Language and Semantics of Verbs 

I'd like to delete "id" from "verb id" in the first hit and "within the Activity" from the second hit. Is there anything else you'd change?

**Comment by garemoko** [comment]
Sorry, I misread. "verb id" is correct.

**Comment by garemoko** [comment]
This should be closeable now.

**Comment by garemoko** [comment]
@andyjohnson this can be closed I think.
