### ISSUE TITLE
Move All IRI Language Together

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#731]
Related to #729 , Part 1 Section 8.3, Part 2 Section 3, and Part 2 Section 4.3 all discuss IRIs.  I propose the following:

Eliminate this part of Part 1 Section 8.3 as it has requirements and could just as easily be in Part 2 Section 3.  This will be expanded to all "coined" IRIs, which are done for metadata purposes anyways.

Part 2 Section 3 takes in all of the language surrounding Generic IRIs and Metadata hosting.  It refers to the Activity Definitions section for the specific rules around those IRIs (these currently make up Section 3.1)

Cut Part 2 Section 4.3 down to the first paragraph, where they are disambiguated from URIs, IRLs, and URLs and reference Part 2 Section 3 there.

**Comment by garemoko** [comment]
I'm planning to look at this once the other PRs are merged so I can make more sense of it, but if you're planning to PR this and want feedback first just let me know.

**Comment by andyjohnson** [comment]
I think that waiting on the other PRs is the most prudent at this point.  I
hate merging conflicts :)

On Thu, Jul 30, 2015 at 2:26 PM, Andrew Downes <notifications@github.com>
wrote:

> I'm planning to look at this once the other PRs are merged so I can make
> more sense of it, but if you're planning to PR this and want feedback first
> just let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/731#issuecomment-126425160>.
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by garemoko** [comment]
This is done except for adding a reference to part 2 section 3 in part 2 section 4.3.

**Comment by garemoko** [comment]
This can be closed now

**Comment by garemoko** [comment]
@andyjohnson close please!
