### ISSUE TITLE
Harmonize timestamp property vs Timestamp and make corresponding edits

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#733]
Per @garemoko 's recommendation, I think we should look at moving as many requirements from the Statement sections on "timestamp" and "stored" into 4.5 ISO 8601 Timestamps as is warranted.  Right now we have a mix of property and data type requirements in each of these sections.

**Comment by garemoko** [comment]
See https://github.com/adlnet/xAPI-Spec/pull/719#discussion_r35668940 and https://github.com/adlnet/xAPI-Spec/pull/719#discussion_r35669346

**Comment by garemoko** [comment]
I believe this is done now.
