### ISSUE TITLE
Fix HTML-Style Links in Document

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#734]
Somewhere along the lines, a stray <a href></a> or two made its way into the document.  I then perpetuated it as a link strategy.  As a pre-release task, lets return to using the []() syntax consistently throughout the document.

**Comment by garemoko** [comment]
One of the reasons for the mixture is the Github markdown doesn't support tables, which have to be done in HTML. Markdown within HTML isn't rendered so any links (or styling) within tables has to be done using html. Lots of the links are within tables.

**Comment by canweriotnow** [comment]
@garemoko I can easily refute that claim:

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

**Comment by garemoko** [comment]
<table>
<tr><td>[It doesn't work for links](http://example.com)</td></tr>
</table>

**Comment by canweriotnow** [comment]
Once again, @garemoko, I refute the assertion.

| Tables        | Have         | Links  |
| ------------- |:-------------:| -----:|
| Hey      | @garemoko  | [link][1] |
| Hey     | @andyjohnson       |   [other link][2] |

[1]: http://4chan.org/b/
[2]: http://clickhole.com

**Comment by canweriotnow** [comment]
>  It is true that if you use html tables, the markdown doesn't work inside though.

Sorry, I misread that originally... I assume this statement is in support of the proposal to excise all HTML tables with extreme prejudice?

**Comment by garemoko** [comment]
It was a statement of corrective fact to my earlier incorrect comment and wasn't intended to be for or against the proposal to replace the HTML with markdown. 

[https://github.com/adlnet/xAPI-Spec/issues/829#issuecomment-160773167](This comment) is in favor of  replacing the html with markdown.

**Comment by garemoko** [comment]
I think this can be closed as a sub-task for #829
