### ISSUE TITLE
Use one type of JWS Serialization. 

### ISSUE THREAD

**Issue by nashyura** [adlnet/xAPI-Spec#736]
There are two types of Serialization defined in the JWS spec: [Compact and JSON](https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#section-3.1)

I have only seen the compact serialization implemented in libraries I've used.  If nobody currently uses the JSON serialization, and there is no need for it in the xAPI spec, it makes sense to explicitly limit the xAPI spec to use the Compact Serialization.

We can modify 1.x to say that signatures SHOULD be serialized using the compact serialization format, and in 2.x we could change that to a MUST.

Of course, this suggestion is not useful if anybody that is adopting the spec uses JSON serialization.

**Comment by garemoko** [comment]
Not sure if @brianjmiller is going to be on today's call, but I look to him for wisdom on this one.

**Comment by andyjohnson** [comment]
Per the 10/4/2015 call, didn't have experts on this topic.  We believe the problem to be that if no Serialization type is chosen, that LRSs would support both.  It therefore makes sense to choose one.  If  libraries are already using compact, it would make sense to choose that one.  This is, again, with the limited understanding we had.  Looking for more information on this.

**Comment by andyjohnson** [comment]
The example in the spec is also compact. (10/4/2015 call)

**Comment by garemoko** [comment]
So I guess the next logical question is do the major LRSs support both today?

**Comment by andyjohnson** [comment]
Really the best we can do is SHOULD* at this point, with a disclaimer that this was always the intent as seen in our examples.

**Comment by andyjohnson** [comment]
With the referenced document being from Jan 2015, dating the references could be valuable as things can change.  Let's look at the other LRSs, but the direction is still SHOULD* for implementing compact.

**Comment by garemoko** [comment]
We can close this now.

**Comment by garemoko** [comment]
@andyjohnson close please!
