### ISSUE TITLE
Introduction 

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#739]
The current Introduction is as follows:
1.0 Summary of the Experience API

The Experience API (xAPI) is an Application Programming Interface (API) specification that facilitates communication about experiences between a Learning Record Store and a client, typically an Activity Provider. This specification was developed with learning experiences in mind, but many other kinds of experiences could be tracked using xAPI.
---------------------
I think that we name of the title to "Introduction to the Experience API" because a summary is something that sums up what has gone before.  We are not summing up anything at this point.  We are introducing the subject.

Second, I think that the phrase "facilitates communication about experiences between a Learning Record and a client, typically an Activity Provider" should be replaced with something more general.  The terms are not defined here and a new reader would be mystified at this point.  Moreover, the specification does far more that facilitating communication - it actually sets out a framework/syntax for describing learning experiences - as well as an application interface for the online storage and exchange for those descriptions.

**Comment by rswetnam** [comment]
whoops - please excuse my shouting - I'm new to Markdown

r.

**Comment by fugu13** [comment]
Definitely agreed on changing to Introduction, preliminarily agreed on generalizing the phrase if we can come up with something that conveys a clear picture while being more general

**Comment by garemoko** [comment]
+1 to what @fugu13 said

**Comment by aaronesilvers** [comment]
How's this for a start?

The Experience API (xAPI) is an Application Programming Interface (API)
that addresses the structure of data describing an activity (currently
expressed with JSON by an "Activity Provider"), the means of sending and
retrieving such data to/from data storage applications (leveraging a
RESTful interface) and the storage and transfer of that data record (via a
"Learning Record Store"). This specification was developed with learning
experiences in mind. As evidenced by the different communities adopting it,
xAPI is employed to track a variety of experiences in contexts such as job
performance, medical and wellness, labor, engineering and compliance.

-a-

---
#*mobile*

Aaron E. Silvers | *MakingBetter* <http://makingbetter.us/>
857.34.BEARD | @*aaronesilvers* <http://twitter.com/aaronesilvers>

Let’s meet! Pick a time <https://doodle.com/makingbetter>.

**Comment by fugu13** [comment]
Hmm, I think that might be cramming too much into the first sentence, though I like a lot of the elements

**Comment by rswetnam** [comment]
The Experience API (xAPI) [is a document that] aims to facilitate the documentation and communication of learning experiences.  It does so by setting out a grammar that specifies how learning experiences should be described and an Application Programming Interface that sets out how information about these experiences should be stored and exchanged electronically.  

The goals of the xAPI are:

* To maximize interoperability of systems which create, gather and store information
about learning experiences.
* To provide a guide to those who want to build applications that conform to and implement this specification.
* To provide criteria against which conformance to this specification can be tested.

**Comment by garemoko** [comment]
@rswetnam I think that loses too much of the content from those first two paragraphs. I'm also not keen on introducing the concept of "grammar" here since we don't use that concept again anywhere.

**Comment by NickWashburn** [comment]
"facilitates communication about experiences between a Learning Record and
a client, typically an Activity Provider" could be "facilitates the
communication of experiences to the Learning Record Store."

**Comment by rswetnam** [comment]
My original concern remains.  People in the loop know what Learning Records and Activity Providers are.  However, somebody not in the loop would have no idea what's being referred to.  We need to introduce the broad concepts of what the document is trying to do.  The xAPI should be for more that a selected priesthood.

**Comment by garemoko** [comment]
@NickWashburn +1 to that. 

@rswetnam What if we go with @NickWashburn's suggestion  and add a link on "Learning Record Store (LRS)" to the explanation. I believe that most people reading even the introduction to the spec will be familiar with the term "LRS", "Activity Provider" is less likely.

**Comment by rswetnam** [comment]
@NickWashburn @garemoko  The purpose of the introduction is to set out in broad terms what we are doing and why.  Suggesting that the purpose of the xAPI is is to "facilitate communication about experiences between a Learning Record and a client, typically an Activity Provider" is limiting and to a certain extent misleading - like saying that the purpose of a book of poetry is to facilitate communication between a MPWF (Mass of Pulped Wood Fibre) and a recipient, typically a Reader.   

I'm not saying that the xAPI is poetry - but surely the purpose goes beyond what is suggested here. 

Moreover, Learning Records don't communicate with agents, they store information about the learning experiences of agents.

However, it is worded, I think the intro should include the following ideas:

* One purpose of the xApi is to set out how learning experiences - [not experiences as the current intro suggests] should be articulated, documented - whatever so that they can be better understood, 
compared, stored  and used as evidence about what people have done to further their knowledge

* Another purpose is to provide a common framework or Application Programming Interface that makes programs which follow this framework more interoperable.

**Comment by jgoodell2** [comment]
I agree with Roger that it is best to set the stage using non-technical language to introduce the "what" and "why" and then start to get in to the technical "how". Here is an attempt to merge Roger and Aaron's versions...

The Experience API (xAPI) is a [technical specification / technology] that aims to facilitate the documentation and communication of learning experiences. It does so by setting out a protocol [and suggested grammar] that specifies how learning experiences should be described and an Application Programming Interface that sets out how information about these experiences should be stored and exchanged electronically.

The goals of the xAPI are:

* To maximize interoperability of systems which create, gather and store information about learning experiences.
* To provide a guide to those who want to build applications that conform to and implement this specification.
* To provide criteria against which conformance to this specification can be tested.

xAPI includes an Application Programming Interface (API) that addresses the structure of data describing an activity, the means of sending and retrieving such data to/from data storage applications and the storage and transfer of that data record.

The technologies used include [JSON](http://www.w3schools.com/json/) for encoding the description of a learning activity, a [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer) interface for communication between applications, and a "Learning Record Store" for storage of xAPI records.

**Comment by NickWashburn** [comment]
I am sorry I have not been totally engaged here. I am certainly would not be biased about this but I think @aaronesilvers post above can be wordsmithed with some spice from the others. I will advocate toward a simple paragraph / almost mission statement to be the result of our collective work here....my attempt


**The Experience API (xAPI) is an Application Programming Interface (API) that specifies the structure of data used to describe activities, and specifies the means of sending and retrieving activity data records to and from storage in the Learning Record Store (LRS). This specification was developed to communicate learning experience data but is also used to effectively track a variety of experiences.**

**Comment by garemoko** [comment]
For those joining the conversation, note that since the early conversation I've made an attempt at synergising these suggestions in a PR. This has now been merged and you can see the results here:

https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#10-summary-of-the-experience-api

I hope that I addressed the issues raised, but if not it might be best to suggest changes to that version rather than going back to the earlier version presented in comments in this discussion.

**Comment by rswetnam** [comment]
Both of the introductions proposed by @garemoko and @NickWashburn are technically correct. However, beyond the small group who have been working on or using the spec so far, I doubt that talking about facilitating communication between a learning record store and an activity provider would mean much to a new reader.  Introducing these terms in the first sentence creates the impression that the document was written only for the initiated.  For this reason , I support the wording proposed by @jgoodell2

**Comment by NickWashburn** [comment]
@garemoko Bravo!

**Comment by aaronesilvers** [comment]
I second the suggestion. I like the edits by @jgoodell2

Sent from Outlook

    _____________________________

**Comment by garemoko** [comment]
There's definitely useful stuff in @jgoodell2 's version, but I think there's a lot of useful stuff that's been cut out too. Was that cutting intentional or the result not looking at the [latest working version](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#10-summary-of-the-experience-api).

Put this in a PR and then we can discuss the details of how this fits with the rest of the document and exactly what it does/doesn't replace.

**Comment by jgoodell2** [comment]
Ok, I may not have seen the latest version when I drafted my suggestion; it is closer my thinking. However, in line with @rswetnam's concerns, I think the first part of the intro should be readable by the uninitiated. The message should be clear that the intent for xAPI is to communicate learning experiences, a second sentence saying it _could_ be used for other things muddy the waters. And jumping into what it is _not_ before finishing saying what it is can be confusing. 

My opinion is that the opening paragraph (or 2) should be understandable by the broadest audience (even those who don't know what "API" means) technical/nontechnical, initiated/uninitiated...Start with a common ground paragraph that can be used to explain the high level reason xAPI exists to all audiences. We don't want to lose anyone on the first paragraph. Then follow with the details (for a smaller audience).

**Comment by NickWashburn** [comment]
xAPI *may* and *is* being used to communicate other experiences. Isn't that important for the uninitiated to understand? I prefer using *may be* over *could be*.

**Comment by jgoodell2** [comment]
@NickWashburn I guess I'm still semi-uninitiated. What kinds of non learning experiences are being captured and for what purposes? Was it ADL's intent for xAPI to reach beyond learning?

**Comment by aaronesilvers** [comment]
@jgoodell2 it was ADL’s intent to open xAPI to ends that reach beyond learning, with the caveat that our domain interests were around learning and performance.

The non-learning experiences that are being captured have a lot to do with regulatory compliance (near-realtime communication from sensors about a driver’s acceleration, speed in controlled settings), task performance (benchmarking against expertise), analytics (not necessary learning analytics, but more like how Google Analytics is employed but in non-web software and mobile contexts).

The work I’m doing consulting is almost a 50/50 split between learning and what I’d couch as “performance” both in terms of what we’re working on consulting-wise and what we’re hearing about from a whole-spec adoption

Let’s meet! Pick a time <https://doodle.com/makingbetter>.

**Comment by garemoko** [comment]
This was fairly extensively discussed on a recent call and #759 is now merged following changes based off that discussion so I believe this issue can now be closed.
