### ISSUE TITLE
Add 2nd Should to PUT and POST for Statement ID conflict

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#740]
The Statement Resource(previously API) has a requirement under PUT and POST that reads as follows:

If the LRS receives a Statement with an id it already has a Statement for, it SHOULD verify the received Statement matches the existing one and return 409 Conflict if they do not match.

The SHOULD actually modifies the whole requirement and is not to be interpreted as a SHOULD then a MUST.  The language is to be updated to:

If the LRS receives a Statement with an id it already has a Statement for, it SHOULD verify the received Statement matches the existing one and SHOULD return 409 Conflict if they do not match.

**Comment by garemoko** [comment]
+1

**Comment by ljwolford** [comment]
So the updated language is just saying the LRS checks the id of an incoming statement...if it already exists it SHOULD see if it matches the existing statement. If they do match, then it's fine and it returns a 204 or 200 depending on the method, and if they do not match the LRS SHOULD reject it and return the 409.....right?

**Comment by garemoko** [comment]
Right. Which is what I think is implied by the existing wording.

**Comment by fugu13** [comment]
Yes, that's been how we've discussed it on calls a number of times, and I think is the most reasonable interpretation of the text on a first read.

**Comment by garemoko** [comment]
This is resolved and can be closed.
