### ISSUE TITLE
Document Structure

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#741]
I'd like to suggest that the first section that includes all the info about revision history be moved to an appendix so that the first section that appears would be the Table of Contents.  I think it would save a great deal of scrolling and make the document more usable.

Roger

**Comment by garemoko** [comment]
+1 This will only get longer.

**Comment by andyjohnson** [comment]
I propose adding the Revision History as the last section of Part 1, the Contributors List right after the Role of xAPI, and the License to the very first section of Part1.  I'm open to other suggestions.

**Comment by rswetnam** [comment]
Currently, Part One: __Summary of the__ Experience API in the TOC links to Part One: __About The__ Experience API in the document and 1.0. __Role of the__ Experience API in the TOC links to 1.0 __Summary of the__ Experience API in the body

**Comment by rswetnam** [comment]
I don't think that Revision History belongs in the main body of the document as it does not contribute to the flow of the arguments being made.  I think it belongs in an appendix.  I think a similar argument could be made regarding the list of contributors.  I think that the list of contributors could be moved to an appendix and replaced with with a brief section setting out how the document has been a collaboration involving many members of the community.   I agree with the placing of the License.  

While my arguments might sound petty, I believe that there is always a cost in placing tangential information in the body of a document in that it detracts from its main thrust and flow - especially when a hyperlink to the relevant appendix makes it easy for those who want to look up this information.  In the case of technical documents - +1 Hemingway -1 Jane Austen

**Comment by garemoko** [comment]
RE: https://github.com/adlnet/xAPI-Spec/issues/741#issuecomment-140751437 
Good catch @rswetnam - I believe the titles in the document are right and the TOC should be changed. I suggest raising this as a separate issue to make sure it doesn't get missed. 

RE https://github.com/adlnet/xAPI-Spec/issues/741#issuecomment-140733797 and https://github.com/adlnet/xAPI-Spec/issues/741#issuecomment-140754866

@rswetnam remember that the three parts will be three documents so putting revision history at the end of part one essentially makes in an appendix to part one - it's the last thing in that document. 

I agree that the contributors list would disturb the flow there. How about we put it at the top of  [CONTRIBUTING.md](https://github.com/adlnet/xAPI-Spec/blob/master/CONTRIBUTING.md) (that file is not in the restructure branch, but is in master). Maybe we could even get an updated message from the new ADL Director alongside the old one, thanking people for continued contributions going forwards. 

Along those lines, we could put the license in a separate LICENSE.md. If it goes in part 1 it should probably go in every part.

**Comment by andyjohnson** [comment]
Per the 9/16/15 - 1)  Would love to split out the license, but worry about copyright/etc. with it not being in each file.  Can anyone give guidance in this area.  2)  We are okay with moving the Contributors to the contributing.md  3)  Perhaps create Revision History as an appendix and assign all appendices to Parts as relevant.

**Comment by andyjohnson** [comment]
Per the 9/16/15 call - Revision History would be an Appendix for part 1, A-C and E would be for Part 2, and D,F, and G for Part 3.

**Comment by garemoko** [comment]
This is covered in PR #775
