### ISSUE TITLE
Carefully review part 2 section 4

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#742]
It seems that https://github.com/adlnet/xAPI-Spec/pull/719 will merge into the restructure branch in an imperfect state as it needs changes that impact other parts of the document. 

This issue is a reminder to carefully review part 2 section 4 (especially the IRI, timestamp and duration sections for duplication) before the restructure branch gets merged into 1.0.3

**Comment by garemoko** [comment]
These are the two actions:
* https://github.com/adlnet/xAPI-Spec/pull/719#discussion_r35668940
* https://github.com/adlnet/xAPI-Spec/pull/719#discussion_r35669346

I also want to: 
* re-read all of part 2 section 4 to check the wording of the new content. 
* reflect on whether 4.3 IRIs is needed.

**Comment by andyjohnson** [comment]
#766 should address this if accepted
