### ISSUE TITLE
Difficulty Understanding Document Flow

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#743]
This morning, I wanted to see if I could help out by making a contribution by reviewing and making suggestions on the Section 7.0 that Andy referred to on last Wednesday's meeting.  I confess to have given up on this because I got very confused about where I was in the document.  There appear to be two section 7s  in different parts of the document - even though the Table of Contents only refers to the first part.  I also had a great deal of difficulty determining what was new and proposed and where they fit in.  A major part of this confusion is no doubt due to my unfamiliarity with GitHub.  However, a major part, I believe has to do with both the current and proposed structure of the document and secondly how the document is presented in GitHub.  

Regarding how the document is presented in GitHub, I would like to suggest that sooner, rather than later, the following be done:
* The current Revision History be moved to an appendix so that The Table of Contents be shown at the top
* The Table of Contents Be Expanded to Show all of the sections included in the document
* Outstanding Pull Requests be included in the appropriate places in the document - even though they may not be fully fleshed out or agreed to.  

It think that by doing this, it will give folks a better understanding of the overall direction/structure of the document.  My concern is that by not having this clearly laid out, we cannot see the forest for the trees and forget the situation of a new reader who is brought from extremely broad generalizations to the smallest minutia without warning or definitions supplied in context.

I will post my suggestions regarding the substantial structure of the document in another issue.

**Comment by andyjohnson** [comment]
Hey @rswetnam thanks for this.  Right now, it is a pain to read cover to cover.  After we get these last 6 PRs merged, I'll be fixing the TOC right away and you can see that the document is split into 3, with the taxonomy of Part/Section/Sub-section.  As a part of this restructure, the spec will actually separate into these 3 documents.  The first document will focus on the "lingo" and concepts, the second on data, and the third on data processes.

**Comment by andyjohnson** [comment]
Looking better @rswetnam ?  Can we close this if we tackle the text above TOC?

**Comment by rswetnam** [comment]
sounds good @andyjohnson - just noticed that I missed your earlier posting.  good to close - +1 Roger - Over and Out
