### ISSUE TITLE
Audience and Document Structure

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#744]
My suggestions regarding document structure reflect my understanding/assumptions regarding the purpose and the audience for the xAPI document.  So before I put forward suggestions regarding the document structure, here are my assumptions regarding purpose and audience.

xAPI aims to facilitate communication about learning experiences and make the exchange and storage of data about these experiences more economical.  It aims to do this in two main ways:
* By putting forward a standard way by which learning experiences should be described so that they may be more easily understood, compared and stored;
* By putting forward an application programming interface, which if followed will make programs that promote and track learning experiences more interoperable and economical. 

xAPI is aimed at two main audiences:
* Educators, policy makers and administrators who need to understand how learning experiences should be described and how these descriptions can used to make understanding and comparisons of different people's learning experiences more meaningful;
* computer programmers who need to build programs that can work together to promote learning experiences and store, exchange and manipulate data about these experiences.

Based on these assumption, I suggest that the document be broken into two major sections:
* **The Description of Learning Experiences**
This section would set out why it is useful to have a standardized way of describing learning experiences and then set out the details of xAPI statements, actors, verbs etc.  It would be written with the idea that it could be understood by educators, policy makers and administrators who would ultimately be responsible for generating these descriptions
* **The Application Programming Interface**
This section would be aimed at computer programmers and would describe the interface that their programs would need to conform to if they were to be interoperable with other computer programs that dealt with learning experiences and which followed this interface.

**Comment by andyjohnson** [comment]
@rswetnam - I'm hopeful we can get there!  We currently have 3 parts - the first intended for those getting their feet wet (I'm not sure it is at the decision-maker level yet, but if we do manage to keep it requirement free, I could see tailoring it more toward that audience.  The other 2 parts are indeed intended for programmers.  There was a bit of dabbling in purpose, but that is mostly gone.

**Comment by rswetnam** [comment]
@andyjohnson Thanks Andy.  I am concerned that without the structure and the purpose of the document made clearly evident to collaborators during the writing process, we will end up with a cryptic tome accessible only to the high priesthood of the xAPI and will not get the traction I think we would all like.  I am also finding that the first section with its "Guidelines to Interpreting" aimed at helping the unwashed get their feet wet does more to muddy the waters than help - to bash this metaphor to death...  I find these helpful notes like the old style of programming where massive notes in the code did more to obscure what was happening than to help other programmers.

At the risk of boring the group with material that you have already covered, I would very much appreciate hearing some discourse on the rationale behind the document structure at today's meeting.  I would also repeat my request for a Table of Contents - that is only two or three levels deep to be placed at the top of the document to help give a better sense of the overall direction of the document.  I'd be happy to try my hand at that after today's discussion.
