### ISSUE TITLE
Authority Conformance

### ISSUE THREAD

**Issue by ljwolford** [adlnet/xAPI-Spec#745]
I was running through a few conformance tests regarding the authority field in a statement. The tests were sending a group as the authority:

```json
"authority": {
    "objectType" : "Group",
    "member": [
        { 
            "mbox":"mailto:bob@example.com" 
        }
    ]
}
```

I believe the group is valid and the test should pass but I came across a line in the Authority section regarding OAuth group:

Authority MUST be an Agent, except in 3-legged OAuth, where it MUST be a Group with two Agents. The two Agents represent an application and user together

I think the test was assuming the LRS would think the authority was an OAuth group and fail since it only has one agent in the member field. I didn't think there was a way to distinguish an OAuth group from any other type of group? Is it possible to enforce the MUST with an OAuth group then?

**Comment by toaster33** [comment]
Maybe the part of authority [OAuth Credentials as Authority](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#requirements-15) "The Agent representing the OAuth consumer MUST be identified by account."

**Comment by fugu13** [comment]
The only kind of Group allowed in authority is a two-legged Group, so it should definitely reject that Statement. It is otherwise required to be an Agent.

**Comment by ljwolford** [comment]
OK, that's how I initially interpreted it but for some reason was thinking that was wrong after one of the meetings. Thanks!
