### ISSUE TITLE
Part 1 Section 7 Graphics and Text

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#749]
These still need some fine tuning, the PR #711 got us really close, but needed to be merged for greater readability of the document.

**Comment by garemoko** [comment]
My outstanding comments on the graphics and text (mainly text now) are [here](https://github.com/adlnet/xAPI-Spec/pull/711#discussion_r38010481), [here](https://github.com/adlnet/xAPI-Spec/pull/711#discussion_r38010970) and [here](https://github.com/adlnet/xAPI-Spec/pull/711#discussion_r38011187).

The second and third are basically "happy with the content, but needs more word smithing".

**Comment by fugu13** [comment]
I think the diagrams are getting very close, though I'd like some tweaks. "sent via" a resource should be made clearer. Really, the "upon request sent via" constructions are ways to hide a separate requester, who we should just add to the diagram.

**Comment by garemoko** [comment]
Suggest the next PR on this also picks up #631.

**Comment by garemoko** [comment]
@andyjohnson I think this is done now?
