### ISSUE TITLE
More Visualizations

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#750]
Per the 9/9/15 call - Add more graphical landmarks e.g. in Verbs, a Statement highlighting the verb as they come into that section.

**Comment by jgoodell2** [comment]
For example, a table showing the _concept_ of a statement with a highlighted column for the part being described:

 |  |  |  |
:---:|:---:|:---:|:---:|:---:
`actor` | _**verb**_ | `object` | `result` |
`“Example Learner”` | _**"attempted"**_ | `"A fictitious example CBT course."` | `"score":{          "scaled":0.95}, "success":true, "completion":true`

(Repeating the visual for different parts of the statement will provide a familiar visual map, with "you are here" cue.)

**Comment by garemoko** [comment]
+1 nice idea

**Comment by garemoko** [comment]
Anybody want to volunteer to take this one on and make a PR? 

For me, this is a nice to have and I don't plan to do a PR for this myself.

**Comment by garemoko** [comment]
Given the lack of interest in anybody volunteering to do this, i suggest we close.

**Comment by andyjohnson** [comment]
I don't want to give up on this quite yet.

**Comment by jgoodell2** [comment]
I think there was some progress on this, but I'll try to carve out some time to contribute something.jim

**Comment by andyjohnson** [comment]
I think one thing we can work on is adding more examples to the GitHub rather than the documentation.  That way we can all contribute ideas in a more open way than being tied down in spec language or in this case, a release.  Closing this issue for 1.0.3.
