### ISSUE TITLE
Moving Version History, etc. below Table of Contents

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#751]
Per the 9/9/15 call - We talked about all of the "stuff" above the table of contents.  There is a long scroll to the table of contents early.  We also need to make sure our course of action makes sense in regards to splitting into 3 documents.  Ben, Jim, and Roger all felt the TOC should be very close to the top.  Ben suggested using the word "Introduction" as the first entry below the current history/contributors Some options:

1)  Split out version history/contributors as a separate document 
2)  Add them to Part 1, "above" the Introduction
3)  Leave them as they are, realizing they probably have to go across all 3 documents.
4)  As an appendix

The group on the call likes option 4 most, followed by option 1.

**Comment by garemoko** [comment]
My least favourite option here is duplicating them across multiple documents.

**Comment by andyjohnson** [comment]
#741 covers this
