### ISSUE TITLE
Agent

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#754]
Section 2.3.2 says than an actor is:
> A mandatory Agent or Group Object.

What is a mandatory Agent?  Are there other types of Agents?  The document contains no definition of an Agent.

**Comment by garemoko** [comment]
I'm sure we've discussed this before (and I thought we'd fixed it but we haven't). What that phrase means is that the property is required and the value of the property is either an Agent object or a Group object. 

This could definitely be clearer. The opening text for the activity and verb sections is much better. +1 to fixing this. 

We define the Agent and Group objects immediately below.
