### ISSUE TITLE
Another approach

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#758]
This weekend, I attempted to put together a pull request for the introductory paragraphs. In doing this and referencing other parts of the document, it brought back to me the great frustration that I had in trying to build a demo LRS based upon the spec.  My frustration stemmed from circular references, terms being used before they were defined and "helpful" extra descriptions that added more noise than signal..

So rather than offering a pull request, I thought that I could best contribute by offering an alternative approach that addressed some of the frustrations that I had coming to the document as a newbie.  To that end, I have created a branch at https://github.com/rswetnam/xapi/blob/master/xAPI.md.    It's very rough with lots of sentence fragments etc. and needs a lot of work.  But for me, at least, it offers a an approach to setting out the purpose, scope and details of the xAPI in a way that would be easier to understand by newbies.  

I look forward to your comments.

**Comment by garemoko** [comment]
Hi @rswetnam - I'd find it much easier to review this if it was a pull request to see what's changed. Whilst readability is a very important goal, we also need to ensure that there's nothing that changes the actual requirements of the specification.

**Comment by joeconradt** [comment]
I like the in-depth explanations, but perhaps the spec should remain clean cut, with added detail where needed. I will admit some parts of the spec had me frustrated. I installed the ADL_LRS to inspect the database schema which gave me a lot of clarification.

**Comment by garemoko** [comment]
@rswetnam Is there anything still to do with this issue or has it been superseded by the discussion around the introduction PR?
