### ISSUE TITLE
re-do description of performance response pattern

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#764]
The description of the performance response pattern is unclear. This should be re-written with particular attention to the example on page 139 of the SCORM 2004 RTE which makes clear that the elements are id:value, not question:answer.

**Comment by garemoko** [comment]
I'll PR this one sometime soon.

**Comment by garemoko** [comment]
The current text says:

>A list of steps containing a step ids and the response to that step. Step ids are separated from responses by [.]. Steps are delimited by [,]. The response can be a string as in a fill-in interaction or a number range as in a numeric interaction.

I propose (changes in bold, will not be bold in actual PR):

>A list of steps containing a step ids and **a description of** that step. Step ids are separated from **descriptions** by [.]. Steps are delimited by [,]. The **description** can be a string as in a fill-in interaction or a number range as in a numeric interaction.

I'm not 100% confident with this change as the text in SCORM describes the second part as a "step answer" and the fact that it can be a numerical range implies that it's intended to represent an answer, however all the examples in SCORM use it to contain a step description. In terms of practical usage my understanding is that nobody used performance interactions in SCORM. They look like they could be useful for task based simulations in xAPI world. 

Anybody got any relevant experience with SCORM here?

**Comment by garemoko** [comment]
Plan B is that we say it can be either a response or a description but I'd like to avoid that if possible!

**Comment by aaronesilvers** [comment]
I'd say @andyjohnson @bscSCORM and I at least have seen our fair share, like when we SCORMed the Bastille years ago. You could say we were SCORM chasers... but since then we've had a pretty SCORMy relationship with the ol' spec...

**Comment by andyjohnson** [comment]
In reading over the SCORM, this is actually more of a value than a description.  In looking over the requirements, what I don't see is that when the id is used more than once (specifically allowed), that the same "step answer" must be used.  This tells me the pairing itself is not unique (despite the terrible example in the documentation).  If the pairing is not unique, it must be a value.

**Comment by garemoko** [comment]
Agree that the requirements and name of the property do imply it's an answer value rather than the description, but the examples clearly use the property to hold a description. I know we've always said with xAPI that requirements trump examples; can we extend that approach to the SCORM spec? 

Is anybody aware of any real world usage of the performance interaction type?

**Comment by andyjohnson** [comment]
Per the 11/18/2015 call, closing issue as we agree that "step answer" is indeed a value, not a description.  Will talk to SCORM tool vendors to see if anyone is indeed implementing as a "description".  This issue can be reopened if such a case is found.
