### ISSUE TITLE
Harmonize Part 2 Section 1 and Part 3 Section 2.1

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#765]
Both of these have the document merging process in them.  Probably keep Part 2 Section 1 short and refer to Part 3 Section 2.1.  It could also be that both are needed as the merging process may be needed to be known in both.

**Comment by garemoko** [comment]
+1 to keeping part 2 section 1 short. This is also an opportunity to tidy up the table that shows generic properties, which is just confusing. 

On that basis part 2 would simply say "Documents are a thing that exist. xAPI doesn't define their data structure. Have fun!"

**Comment by garemoko** [comment]
This is done.
