### ISSUE TITLE
Link to Extensions Section

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xAPI-Spec#768]
Link in section 2.4.5 to the extensions section is broken:

https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#miscext

**Comment by jhaag75** [comment]
Also, link to API Version is also broken//not functional: https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#apiversioning

**Comment by andyjohnson** [comment]
Thanks!  Got them now.

**Comment by jhaag75** [comment]
There were a few others. We probably need to do a click through QA
throughout the spec.

-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by andyjohnson** [comment]
Closing as the latest sweep should have taken care of all links.
