### ISSUE TITLE
What color do we paint the bikeshed?

### ISSUE THREAD

**Issue by canweriotnow** [adlnet/xAPI-Spec#776]
Now that I've raised the issue in #767, I think it is of paramount importance that we put all other discussions aside to determine what color to paint the bikeshed. 

I'm sure @aaronesilvers and @brianjmiller will have their own valid opinions, but I'm a fan of cerulean.

Thoughts?

**Comment by blakeplock** [comment]
Salmon.

**Comment by craigwiggins** [comment]
Taupe.

**Comment by canweriotnow** [comment]
No, @blakeplock I think a salmon-colored bikeshed might interfere with UUID generation.

**Comment by canweriotnow** [comment]
@craigwiggins I do believe taupe would place the burden of UUID generation on the AP and possibly interfere with HTTP Basic Auth vs. OAuth 1.0 vs. OAuth 2.0 vs. BroAuth 0.9a considerations, perhaps you should consult @rswetnam and @garemoko before considering such a bold choice.

**Comment by aaronesilvers** [comment]
I have a salmon colored sportcoat so +1 @blakeplock

**Comment by canweriotnow** [comment]
I have a 4th Doctor scarf, hat, and sonic screwdriver now, so I'd like that to be considered in the color scheme, or else I'll get in my TARDIS and prevent any of you from being born... unless you can explain the Blinovitch Limitation Effect ITT.

**Comment by blakeplock** [comment]
That might be the effect that @aaronesilvers's sportcoat had on me.

**Comment by canweriotnow** [comment]
No, @blakeplock, just a property of time travel. You need to know these things, we have the only LRS with time travel built into the database :smile:

**Comment by aaronesilvers** [comment]
@craigwiggins recommend labeling this issue as "Question."

**Comment by andyjohnson** [comment]
Mauve

**Comment by aaronesilvers** [comment]
Mauve… ok, Rainbow Dash

**Comment by canweriotnow** [comment]
OMG PONIES

**Comment by canweriotnow** [comment]
Thanks @andyjohnson for applying the proper labels to this issue. The bike shed is an issue that everyone can have an opinion on and therefore really be our primary concern for the next 10-15 years.

It might be advisable to create a "bikeshedding" issue label and apply it to ~90% of the other open issues.

**Comment by garemoko** [comment]
I'm fine with cerulean.

To make a serious response to this point. As we're working on a patch version, we can expect the issues being tackled to be relatively minor. It is good to be reminded not to get too worked up about the details, but we do need to still take care with these trivial issues not to accidentally break something. Also remember that whilst many of the open issues seem trivial, most have come from actual questions by people implementing the spec.

**Comment by garemoko** [comment]
Pretty sure we can close this :-)

**Comment by andyjohnson** [comment]
Fine, but the answer was indeed Mauve.
