### ISSUE TITLE
Preserve Legacy Text on Interoperability/Purpose

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#780]
There are two main ways that the xAPI promotes interoperability between systems that implement the specification. The first is by requiring that systems implementing the specification follow a consistent data structure. To that end, this specification defines a data model for various data objects that are transferred between systems. The most significant object within the xAPI data model is the Statement object. This specification defines the properties of the Statement object (including "Actor", "Verb", "Object", "Result", and "Context") and the rules of syntax for the values of those properties and how they are represented.

The second way that the xAPI promotes interoperability is by setting out the transfer methods that must be used when communicating information about learning experiences between programs that adhere to the specification. As part of this, it sets out the format of requests and the expected responses. Note that the systems storing or retrieving records need not be Activity Providers. LRSs can communicate with other LRSs, or systems. xAPI follows the guidelines of the REST software architecture style, and as such data is tranferred via HTTP requests and responses. xAPI also defines security methods allowing for the trusted exchange of information between the Learning Record Store and trusted sources.

The Experience API is the first of many envisioned technologies that will enable a richer architecture of online learning and training. Authentication services, querying services, visualization services, and personal data services are some examples of additional technologies which the Experience API is designed to support. While the implementation details of these services are not specified here, the Experience API is designed with this larger architectural vision in mind.

**Comment by garemoko** [comment]
I think we agreed on the call that the third paragraph here could get the axe. We just need to find a new home for the first two.

**Comment by garemoko** [comment]
I suggest putting those first two paragraphs at the end of part 1 section 5 xAPI Components under the heading "Interoperability Between Components"

**Comment by andyjohnson** [comment]
Per the 10/4/15 call, part 1 section 5 is good.  Roger said he wanted to add t"xAPI Ecosystem" to Part 1, could be a fit there.

**Comment by garemoko** [comment]
This can be closed.
