### ISSUE TITLE
Update verb example.

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xAPI-Spec#785]
We should use a better IRI example. Perhaps the actual verb passed IRI, http://adlnet.gov/expapi/verbs/passed

Parenthesis are not a good example either as the vocabulary group is providing practices for IRI design with upcoming vocab spec. For the time being, can we updated this example to remove the parens and putting context into the IRI?

https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#verb

Example

This example shows a Verb with the recommended properties set.

{
    "id":"http://www.adlnet.gov/XAPIprofile/ran(travelled_a_distance)", 
    "display":{
        "en-US":"ran",
        "es" : "corrió" 
    } 
}
The Verb in the example above is included for illustrative purposes only. This is not intended to imply that a Verb with this meaning has been defined with this id. This applies to all example verbs given in this specification document, with the exception of the reserved Verb 'http://adlnet.gov/expapi/verbs/voided'.

2.4.3.1 Use in Language and Semantics of Verbs

Details

Semantics

The IRI represented by the Verb id identifies the particular semantics of a word, not the word itself.

For example, the English word "fired" could mean different things depending on context, such as "fired(a weapon)", "fired(a kiln)", or "fired(an employee)". In this case, an IRI identifies one of these specific meanings.

The display property has some flexibility in tense. While the Verb IRIs are expected to remain in the past tense, if conjugating verbs to another tense (using the same Verb) within the Activity makes sense, it is allowed.

**Comment by garemoko** [comment]
In other places we used the example verb "http://example.com/xapi/verbs#defenestrated" as a clearly made up verb. 

Google Translate doesn't tell me what the Spanish is and thesaurus.com doesn't help me either.

**Comment by andyjohnson** [comment]
I agree with cleaning this up.  Nonsense verbs are good.  Putting more than a single token (to help defeat the notion that all verbs are a single "word") is also good.

**Comment by garemoko** [comment]
Defenestrado

https://twitter.com/promanos3/status/668742114860253184

**Comment by garemoko** [comment]
I think this can be closed now?

**Comment by jhaag75** [comment]
Yes, thanks!
