### ISSUE TITLE
Typo in graphic

### ISSUE THREAD

**Issue by brianjmiller** [adlnet/xAPI-Spec#797]
![screen shot 2015-11-18 at 3 19 35 pm](https://cloud.githubusercontent.com/assets/95960/11254715/e32382ea-8e07-11e5-8e3f-9300ccf6935b.png)

**Comment by andyjohnson** [comment]
Thanks!  Will grab this.

**Comment by garemoko** [comment]
@andyjohnson this still need fixing.

**Comment by andyjohnson** [comment]
doh!  I updated it in the source, but didn't push it out.  I'll grab this
when i can.

On Wed, Mar 2, 2016 at 6:07 AM, Andrew Downes <notifications@github.com>
wrote:

> @andyjohnson <https://github.com/andyjohnson> this still need fixing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/797#issuecomment-191189963>.
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by garemoko** [comment]
This is now done: https://github.com/adlnet/xAPI-Spec/pull/901
