### ISSUE TITLE
change LRS requirement to AP requirement 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#801]
I feel like the following requirement would make more sense as an AP requirement:  "An LRS MAY accept small corrections to the Activity’s definition. For example, it would be okay for an LRS to accept spelling fixes, but not to accept changes to correct responses."

The replacement requirements could be:
* An Activity Provider MAY make small corrections to the Activity’s definition in subsequent statements e.g. to fix a spelling.
* An Activity Provider SHOULD NOT make significant changes to the Activity’s definition in subsequent statements e.g. changes to correct responses.

**Comment by andyjohnson** [comment]
I agree with this re-write.  The original requirement suggested enforcement without a requirement.

**Comment by garemoko** [comment]
Looking at this again, I think I understand why this was an LRS requirement originally, but the word "accept" is misleading. It's not about the LRS accepting or rejecting statements, it's about whether or not the LRS updates it's definition. I've made a PR to update the language but keep this as an LRS requirement.

**Comment by canweriotnow** [comment]
@garemoko Wouldn't this potentially affect the immutability of Statements, i.e., if the Activity was updated and the including Statement retrieved later, it wouldn't be identical?

I'm not against the idea, in fact in my view it would open the door to resolving other issues vis à vis the sacrosanct immutability of Statements, such as associating multiple IFIs with the same Agent, but I want to make sure what's happening here is made as explicit as possible.

**Comment by garemoko** [comment]
@canweriotnow there's a number of [exceptions to statement immutability](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#231-statement-immutability) based around the concept that these elements are not technically part of the statement. 

Variations in activity definition and the immutability problems this would cause for distributed systems with multiple LRS are covered by the [Statement GET format parameter] which specifies whether to use the canonical activity definition or the exact one used in the original statement. When moving statements between LRSs, [exact is the format to use](https://github.com/adlnet/xAPI-Spec/issues/760).

This particular PR isn't intended to introduce anything new or change behavior in anyway. It's simply translating a slightly oddly worded requirement  about what the LRS can "accept" from an AP into requirements for what the AP is allowed to send. the rational is that this makes the requirement clearer and that it would be difficult/impossible for the LRS to enforce.
