### ISSUE TITLE
List of Words to Normalize

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#831]
Starting this issue with words that have multiple forms throughout the document - this can be grammatical, spelling differences, or capitalization differences.  These can be easily missed by spell checks:

behavior/behaviour

**Comment by garemoko** [comment]
It might be worth checking all common US/UK spelling differences:

color, anything ending in -ize,

**Comment by garemoko** [comment]
I did a search through the document for "behaviour", "colour" and "ise" - nothing needs changing.
