### ISSUE TITLE
Style guide errors re code/retval markdown

### ISSUE THREAD

**Issue by canweriotnow** [adlnet/xAPI-Spec#838]
In the [Expected Values][ev] section of the `CONTRIBUTING.md` style guide, the examples use triple-backticks for inline code/retval example. In Markdown (and, _a fortiori,_ Github-Flavored Markdown), triple backticks are used for code blocks, such as:

    ```clojure
    (defn hey-there []
      (println "I'm a Clojure function"))
    ```

As opposed to the example, which uses:

```
Here's a piece of ```code``` or whatevs
```

Which should be 

```
Here's a pice of `code` or whatevs
```

I planned on fixing this in my markdown cleanup, but since it's a content problem figured it should have a separate issue flagging it.

[ev]: https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/CONTRIBUTING.md#expected-values

**Comment by garemoko** [comment]
+1. I never knew you could use the single ticks inline. 

I'm in favor of fixing the style guide and the document for this particular issue as a single PR.

**Comment by canweriotnow** [comment]
Cool, will separate that out.

**Comment by canweriotnow** [comment]
Oh, wait, I might have misunderstood you: did you mean _don't_ separate the style guide revision into a separate issue/PR?

**Comment by garemoko** [comment]
No, I think you understood the first time. 

generally speaking, I'm in favor of as many and as small PRs as possible, but I'm suggesting grouping the style guide changes to the related document changes so that each version of the document, before and after PR, is coherent.

**Comment by garemoko** [comment]
@canweriotnow are you planning to tackle this one? I care enough about this to +1 it if you PR it, but not enough to do the PR myself :-)

**Comment by Asoul** [comment]
I have changed the Markdown syntax to @canweriotnow recommended

**Comment by garemoko** [comment]
This is done and merged; it can be closed.
