### ISSUE TITLE
Should we reference SCORM in our introduction?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#848]
The 2nd and 3rd paragraphs of our introduction are about SCORM. Should we give such prominence to SCORM in the introduction. 

Mark Spivey recently tweeted `#xapi if u dont want to be seen as the "next scorm" then dont use market positioning asserting contrasts to #SCORM & its related mindset` https://twitter.com/markjspivey/status/676863670769418241

Does he have a point in this case?

**Comment by canweriotnow** [comment]
Hell hath no fury like an xAPI'er SCORM'd.

I.e., hells to the no ;)

**Comment by vreten** [comment]
In a recent presentation we compared them and said it was like comparing a
rotary phone and a smartphone.  I think the audience understood the
reference.
patrick

**Comment by andyjohnson** [comment]
I'm really torn on this, as our result core is based on SCORM, so having the background isn't bad - at the same time, "rotary phone 2.0" doesn't sound great.  The sentence that somewhat glorifies SCORM could be toned down a little, but let me get a vibe from ADL leadership how strong she wants this tie to be.

**Comment by vreten** [comment]
Its hard to compare in an elegant way without going down the rabbit hole of
formal course tracking versus tracking experiences.

**Comment by garemoko** [comment]
We now only mention scorm once in part 1, and that's in the change log.
