### ISSUE TITLE
Learning Record Provider or Activity Provider

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#852]
We discussed this in some length on the 12/16/15 call and agreed to sleep on it.  I also said I would write a potential narrative.  I wanted to try to approach this from multiple angles, one where learning experiences occur within activities and one that doesn't use activities.  I couldn't get my head around how not to use, activities, however, with them being called out so many times in the spec.  The following is I how I feel xAPI should be approached in terms of calling out components.  I'm open to how accepted "Activity Provider" is in practice versus how "Learning Record Producer/Provider" could fit in nicely with the other "Learning Record" terms.  The group mostly felt Learning Record Interpreter was good.

"xAPI enables the tracking of learning experiences. xAPI does not restrict learning experiences in any way, but to track them, Learning Records are created to provide evidence of the happenings within the learning experience.  The tracking environment construct in which this reporting occurs is called an Activity.  Activities are uniquely identified and are often located at resolvable addressesl  The learning experience itself need not take place in or at this Activity (although commonly, it will), but the xAPI tracking DOES need to be done within the Activity.

An Activity Provider is uniquely situated to produce Learning Records that connect a user to learning experiences within an Activity.  The user, experience, and Activity Provider all trust each other.  The Activity Provider is responsible for the formatting and population of a Learning Record that meets xAPI requirements.  These Learning Records can then be transmitted to a Learning Record Store (LRS).

A Learning Record Store is responsible for allowing storage and retrieval (with limited search capability) of Learning Records.  An LRS and an Activity Provider have a trusted relationship with certain permissions granted to the Activity Provider by the LRS.  A Learning Record Interpreter, also having similar permissions-based trust with the LRS, can access Learning Records for which it is authorized to do so.  The Learning Record Interpreter can use Learning Records for a variety of purposes, whether it be analysis, compilation, sorting, or re-routing.  A Learning Record Interpreter can perform query-based searches using an interface provided by the LRS.  

Note:  Activity Provider, LRS, and Learning Record Interpreter are all roles within xAPI.  An xAPI solution, tool, or system may have multiple components filling the same role and/or a single entity serving in multiple roles."

**Comment by garemoko** [comment]
I don't understand how you're using the term "activity" in the 2nd paragraph. Did you mean "Activity Provider"?

**Comment by andyjohnson** [comment]
Nope, I do actually mean "Activity", specifically an Object with the type Activity, but in descriptive language, just "Activity".  My point in this is xAPI doesn't really care where the actual learning takes place, but the tracking is done (typically, and especially in terms of traditional e-learning) inside of one of these Activities.  I'm also trying to decouple the content layer from the tracking layer, as they may not be the same.  The Activity Provider is responsible for the tracking within the Activity, and could be responsible for the learning, or could hand that portion off to another source, but it retains the authority to interact with the LRS.

**Comment by garemoko** [comment]
I think the opposite is true. The activity is where the learning takes place, though tracking data about that activity may be captured and/or transmitted via a separate tool. The Activity Provider is the complete system including the part providing the activity and the part(s) capturing and transmitting the tracking data.

**Comment by garemoko** [comment]
Just a thought: one argument against the term "activity provider" was that xAPI addresses the system that sends tracking data, not the system that provides the activity and they could be separate systems. That same argument actually applies to "Learning Record Producer" because the component that produces the learning records could be separate from the component that transmits them to the LRS. H5P is an example of this. 

My point is this: any term is going to have some issues and not exactly match the areas in and out of xAPI scope.

**Comment by andyjohnson** [comment]
This was my worry about the current definition of Activity Provider, that it is indeed both parts as you describe.  I think the two need to be separated as we really don't talk about the fact that a content developer is still going to need to either be trusted by the LRS or utilize a component that is - one that connects the learner to the trusted content.. I think that defining the "Activity" in the spec as the place where tracking is done (and possibly learning too) can get to that point.  I agree that at this point, either definition introduces complexity.  I like Activity Provider less if we can't make a distinction between content and tracking layers of an Activity.  I think we can only put the Activity Provider on the hook for supplying the tracking portion.

**Comment by rswetnam** [comment]
For me, the term "Activity Provider" is meaningless.  An activity is something that happens.  We can provide a book, a room and some light but we can not provide the activity of reading a book.  That only happens when a person picks up a book, looks at it and starts interpreting the symbols on the page to something meaningful for himself/herself.

In the Experience API, there is a component that is responsible for describing the activity - in this case reading a book -  and formatting that description into a record that is sent and added to a Learning Record Store.  That component is an Activity Record Provider, or better still, a Learning Record Provider.

**Comment by NickWashburn** [comment]
Suggest
An Activity Provider is uniquely situated to produce Learning Records that track learning experiences within an Activity.

**Comment by garemoko** [comment]
I like that @NickWashburn.

**Comment by andyjohnson** [comment]
Ditto, that is good @NickWashburn

**Comment by andyjohnson** [comment]
The group on 01/06/16 decided to strongly consider Learning Record Provider, but keep references of Activities themselves (due to breaking changes).  Independent evaluations will follow as comments on this thread.

**Comment by andyjohnson** [comment]
Also, strongly revisiting Learning Record Consumer instead of Interpreter, because really it is "Reading", but Learning Record Reader sounds funny.

**Comment by garemoko** [comment]
The definition has been updated, but this needs to be replaced throughout the documents.

**Comment by andyjohnson** [comment]
This is part of a wider definition sweep, so we can close this.
