### ISSUE TITLE
Best way to represent partial success?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#856]
If a question is partially correct, how does the spec expect that to be represented? 

My answer is that success is false but the (scaled and/or raw) score is a non-zero positive number. 

I don't think this requires any changes to the spec, I just wanted to asked the question and document the answer here.

**Comment by andyjohnson** [comment]
Per the 2/17/16 call, not using "success" indicates something other than success and failure.  A non-zero score is a good indication.
