### ISSUE TITLE
Consistency Throughout Document for Definitions

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#857]
Description fields throughout the document should be improved and some could potentially be removed.

**Comment by andyjohnson** [comment]
Add links back to the definitions as well

**Comment by garemoko** [comment]
@andyjohnson I'm not clear on what needs doing for this one, so leaving it for you to either address, explain more or close.

**Comment by andyjohnson** [comment]
So an example would be in my latest PR #889 , where the Description at 2.0 adds nothing, and if anything is re-iterated in the very next section.  There are places where we try to offer a "laymen's" description followed by another technical description.  Parts 2 and 3 should be more about the technical solution, so removing these sections where they are repetitive or unhelpful is warranted.

**Comment by andyjohnson** [comment]
Still working this, grabbing Data.md next.
