### ISSUE TITLE
Replace "cannot use attachments" with "does not send the contents of attachments"

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#858]
The [Requirements for Attachment Statement Batches](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#requirements-for-attachment-statement-batches) allow for LRSs responding to a GET request where the attachments flag is true to respond in two different ways. In the response includes attachments then the response is multi-part/mixed, if fileUrls are used then the response is application/json. 

(Side note: I take this to mean not that the LRS is allowed to choose to include either actual attachments or fileurls, but that the LRSs response is determined by the statements that happen to be  in the batch, because immutability. This could be clearer). 

We don't say how the LRS can/should respond if there are no attachments at all. Presumably either approach is OK. Should we make a recommendation one way or another for consistency? I think I'd lean towards using application/json.

**Comment by fugu13** [comment]
The specification is already clear on this, in the statement retrieval section, in the table where it has the attachments parameter:

> If true, the LRS uses the multipart response format and includes all attachments as described previously. If false, the LRS sends the prescribed response with Content-Type application/json and cannot use attachments.

The format is solely determined by the attachments parameter. It has nothing to do with the contents of the Statements. I think we could clear up "cannot use attachments", though. It would be clearer if it said "does not send the contents of attachments".

**Comment by garemoko** [comment]
@fugu13 thanks. I'm sure I looked at that table first; not sure how I missed that!
