### ISSUE TITLE
Transmission Format is capitalized but not named

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#859]
In Part 2, 2.4.11 Attachments, Transmission Format is capitalized as though it is some named thing, however the section Requirements for Attachment Statement Batches does not use the term. 

Triangulation of "Transmission Format described above/below" means that 'Transmission Format' must related to the Attachment Statement Batches section, but it's not clear whether it applied to the whole section or to just one of the options presented. I assume it applies to the whole section. 

Related to #858

**Comment by garemoko** [comment]
Possible solutions:

1. Use "transmission format" instead. 
2. Coin the term Attachments Transmission Format and rename "Requirements for Attachment Statement Batches" to "Requirements for Attachment Transmission Format".

**Comment by andyjohnson** [comment]
When text is done as a part of #868, grab this issue as well
