### ISSUE TITLE
rename xAPI-Processing.md

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#866]
I think it's important to get file names right before we do a release or get too far into edits even. 

I propose xAPI-Communication.md as this is about the communication of data between the AP and the LRS.

**Comment by andyjohnson** [comment]
I went ahead and did this as I agree it is a better starting point.  If anyone else wants to throw a name out there, we can debate in future PRs.

**Comment by garemoko** [comment]
Thanks!
