### ISSUE TITLE
multipart/mixed vs. application/json response

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#868]
There's some stuff in the attachments section of part 2 about multipart/mixed responses that belongs in part 3. IMHO the part 3 section on this shouldn't really be able attachments per se but should be about multipart/mixed vs. application/json responses. 

Even if attachments aren't used, the LRS still returns multiple/mixed if the attachments flag is true, and the activity provider (not client!) can still send multipart/mixed results even when not using attachments so this format really isn't specific to attachments, even though thats what it was created for.

**Comment by andyjohnson** [comment]
Per the 2/17/16 call, text will be moved, any additional text in regards to LRS reacting to Content Types will be considered in 1.1.  Question would be whether to give LRSs the latitude to reject multipart/mixed Statements with zero attachments (would expect that LRSs would handle this case normally).  "An LRS SHOULD* accept Statements with zero attachments that are of type multipart/mixed"
