### ISSUE TITLE
Improved Reading Options: Sync Spec with GitBook?

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xAPI-Spec#893]
For improved readability we might want to consider synchronizing the core xapi spec with gitbook once all of the 1.0.3 updates are made. It provides useful stats, but also allows people a better alternative reading experience to github with a persistent table of contents, alternative formats (PDF,EPUB,MOBI),readability on mobile devices, etc. Just a thought...

https://adl.gitbooks.io

**Comment by garemoko** [comment]
My initial reaction here is 'no' because:

* I think the spec's markdown format with TOC is fairly well organized and accessible as is.
* I assume that this would require a bunch of reformatting, which is a lot of work and risks accidental changes. 
* I don't trust GitBook to be around/free for any particular length of time.

Definitely open to debate on all of those points.

**Comment by jhaag75** [comment]
- Others that haven't worked on the spec have verbally complained about
   the readability and the static TOC being at the top of the document. (e.g.,
   long scrolling, no interactive elements such as pagination, fixed TOC,
   etc.). I brought this up as a possible thing to consider for the community,
   but isn't a dire emergency anything. Just a recommendation for improving
   usability and readability of the spec as an electronic file.
   - It could involve some reformatting. My only experience is porting it
   over from google doc > markdown. There could definitely be some changes
   that would require a strong QA review. I was trying to propose doing this
   while during the recent QA of 1.0.3 since it was already being heavily
   reviewed again. Perhaps this is a bad idea if 1.0.3 review is complete by
   now.
   - Well it is synchronized with a github repo so even if gitbook isn't
   around/free forever it is still there (and could be published to many other
   formats really from markdown).


-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by andyjohnson** [comment]
Closing per @jhaag75 conversation.
