### ISSUE TITLE
Executing PUT On Activity State/Profile & Agent Profile That Don't Exist

### ISSUE THREAD

**Issue by DavidTPate** [adlnet/xAPI-Spec#895]
I wasn't able to find any concrete language on the intended behavior of the Document APIs when dealing  with executing a PUT on an Activity State/Profile or Agent Profile which don't currently exist. In the event that this occurs what is the expected behavior? It starts to get a little bit complex when thinking about the concurrency controls that are in place and it could lead to some really odd interfaces.

When I execute a PUT on one of the document APIs for something that doesn't exist what is the expected behavior?

**Comment by garemoko** [comment]
The LRS will store it, assuming it's been passed an If-None-Match header in the case of agent profile and activity profile resources.

**Comment by DavidTPate** [comment]
Gotcha, and if it is passed a `If-Match`header for an item that doesn't exist yet then it would reject that I'm guessing.

That all makes sense, just think it needs to be codified. Closing this as #896 should help to clarify more once completed.

**Comment by garemoko** [comment]
Yeh, because it wouldn't match.
