### ISSUE TITLE
SHA2 encoding

### ISSUE THREAD

**Issue by rchadwic** [adlnet/xAPI-Spec#904]
Could we specify the encoding form for the SHA2 in the signature metadata? As far as I can tell, the hash is only used to match the metadata to the attachment via the multipart headers, so I don't think the actual encoding actually matters - it could probably be a random GUID. However, the existing LRS assumes the encoding for the SHA2 is base64, and won't accept the statement if the hash is represented in octal.

**Comment by fugu13** [comment]
@rchadwic it isn't base64, it is hexadecimal. Or at least, it should be; not sure which LRS you're referring to. The convention is so strong for representing hashes as hexadecimal in non-binary formats that it wasn't specified, but I'm entirely okay with adding that clarification.

**Comment by rchadwic** [comment]
@fugu13 I agree. My initial guess was that it would be hex, but lrs.adlnet.gov will only accept it in base64. Sorry - I should have said hex before, not sure where I got "octal". This is probably more of an issue for the LRS, but it can't hurt to be super explicit in the spec.
