### ISSUE TITLE
409 Conflict statement comparison SHOULD vs MAY

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/xAPI-Spec#912]
We currently have this `SHOULD`:

>If the LRS receives a Statement with an id it already has a Statement for, it SHOULD verify the received Statement matches the existing one and return 409 Conflict if they do not match.

I question whether this is enough of a best practice to warrant being a `SHOULD` vs a `MAY` because:
* It's a viable strategy to build an LRS in a distributed manner which makes it impossible to implement this requirement. (And at least Wax LRS does so).
* Comparison is hard. Even though we've worked on clearing that up we've tended to do so by aggressively considering different serializations non-equal (eg: `PT120S` vs `PT2M`). The potential for false negatives seems to outweigh the benefit. We could create a list of specific properties to include or exclude in this comparison, but is that worth doing?

I suggest that we change this requirement to a `MAY` and also give each LRS substantial latitude in determining what is and is not equivalent for the purpose of this `MAY`, since if this feature is useful at all it seems to be only as a debugging tool for content. Interoperability seems less important for that use case.

**Comment by garemoko** [comment]
Without explicitly taking a view in favor or against this proposal yet, some thoughts:

- Comparison, whilst hard, is something that we need to solve anyway for the purposes of statement signing. 
- It's fairly easy to accidentally send the same statement id twice for totally different statements when testing statement designs with something like postman. It's much less likely in statements coming from an application without a serious problem that would get noticed pretty quickly. 
- I definitely want to err on the side of false negatives than false positives. 
- Do we also want to consider the case of a batch of statements that uses the same id multiple times? In that particular case, it's very clear cut that something is wrong.

**Comment by bscSCORM** [comment]
We have this:
> If the LRS receives a Statement with an id it already has a Statement for in the same batch, it SHOULD* verify the received Statement matches the existing one and SHOULD return 400 Bad Request if they do not match. See Statement comparision requirements.

The second SHOULD should also probably be SHOULD* (and in 2.x we'd probably be better off just specifying that any repeated statement ID in a catch is a bad batch).

**Comment by andyjohnson** [comment]
The requirement changed slightly from 1.0.2 to 1.0.3:

"If the LRS receives a Statement with an id it already has a Statement for, it SHOULD verify the received Statement matches the existing one and SHOULD return 409 Conflict if they do not match. See Statement comparision requirements."

I think the first SHOULD should be a MAY, to @bscSCORM 's points.  It also seems like there is a larger problem if the ids are not unique, which the LRS may have an entire process for dealing with and making it do a comparison for on-the-spot doesn't add a lot of value.  The second SHOULD should remain a SHOULD as if you go through the comparison, it doesn't hurt to return the 409.

**Comment by andyjohnson** [comment]
Per the 4/20/16 meeting, if an LRS does detect an existing Statement conflict, it should be allowed to go all the way, could be stronger.  Let's get a PR to look at the specific language between the versions.

**Comment by andyjohnson** [comment]
Also per the 4/20/16 meeting, agreement that batches can have tougher language.

**Comment by garemoko** [comment]
Fixed in https://github.com/adlnet/xAPI-Spec/pull/918

**Comment by andyjohnson** [comment]
Jumped the gun, this will be merged shortly (hopefully)

**Comment by andyjohnson** [comment]
Lost the reference for #918, instead became #922 which was merged
