### ISSUE TITLE
Ready for PR: requirement should be in part two

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#913]
The requirement "Statements and other objects SHOULD NOT include properties with a value of an empty object." in part 1 belongs here instead: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#dataconstraints

**Comment by andyjohnson** [comment]
Agreed, let's grab this once the two open PRs referencing the two sections in question are merged.

**Comment by garemoko** [comment]
Ready for PR if anybody wants to grab it!

**Comment by garemoko** [comment]
Theres a PR up with two +1s so closing this whilst i remembered.
