### ISSUE TITLE
Add additional anchor tags to document 

### ISSUE THREAD

**Issue by creighton** [adlnet/xAPI-Spec#941]
The team working on the ADL LRS Test Suite would like to add additional anchor tags to the document to allow them to link directly to a requirement in the specification from the test suite.

They initially looked at the existing anchors in the spec and found that they were a little too generalized - usually marking major sections. This means that users following these links would still need to search a section to find the specific requirement.

GitHub also generates anchors for each Markdown header. But again, these are for headers, not specific bullets or table rows where the requirements are listed. Also these are based on the header contents and may possibly change, which would break any referenced links.

The team will create these anchors, which will have no functional change to the spec or visible change to the rendered Markdown, and generate pull requests in the working branch (currently 1.0.3). 

Before we start, are there any concerns or issues with adding anchor tags or our approach?

**Comment by garemoko** [comment]
No concerns here. Just take care to use html within html tables and markdown elsewhere.

**Comment by stevenvergenz** [comment]
Fixed with PR #944
