### ISSUE TITLE
Should the list of statement ids returned have to be in the same order as statements sent?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#949]
For 1.1. 

See https://groups.google.com/a/adlnet.gov/forum/#!topic/xapi-spec/tK_GHYgKjAY

**Comment by DavidTPate** [comment]
I would think this would be required. Let's say that I sent 3 Statements via `POST /statements` and I don't include any value for `statement.id` which is valid based on [this](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#requirements-1):

> Ids MUST be generated by the LRS if a Statement is received without an id.

Then the only way I would know which statement id goes to which statement (possibly to use it for a `StatementRef` or `Voided` statement) would be based upon the order.

**Comment by garemoko** [comment]
Perhaps this can be a SHOULD* in 1.0.3 actually.

**Comment by fugu13** [comment]
I don't think there's any reasonable reading of the spec where this isn't already an implied MUST; without it, the returned IDs are nearly useless. I'd also thought this had previously been discussed (with action item to add), though probably on a call so I doubt there's a record, and my recollection isn't strong enough to be confident I'm not conjuring things.

**Comment by brianjmiller** [comment]
@fugu13 👍 , see #378 and #517.

**Comment by garemoko** [comment]
PR merged. Closing
