### ISSUE TITLE
Really minor, but xAPI vs. the xAPI

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#964]
Is it important to be consistent in using "the" in front of xAPI?  We see this in specs all the time, so it may not be a big deal.

**Comment by garemoko** [comment]
I use "xAPI" to refer to the concept/idea/thing and "the xAPI specification" to refer to the document specifically.

**Comment by andyjohnson** [comment]
In re-reading, I couldn't find any that stood out as problematic, closing.
