### ISSUE TITLE
Stray MUST?

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#965]
In Communication, under O-Auth Endpoints, we have the following text:

Note that the parameters "consumer_name" and "scope" are not part of OAuth 1.0, and therefore if used MUST be passed as query string or form parameters, not in the OAuth header.  

This whole section is for guidance, but maybe this should be listed as a requirement, not in the intro.

**Comment by garemoko** [comment]
Yeh, it's a bit weird where it is anyway. +1 to moving down to the requirements section and getting rid of the sub heading it sits under.
