### ISSUE TITLE
Distinguish Profiles from the Agent and Activity Profile Resources

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#967]
The Profile definition in the About section could potentially use this clarification.  The word "profile" is very different if you read each book as the About section is strictly about use in CoPs and Communication section sees it as a part of a Resource.

**Comment by garemoko** [comment]
In 1.0.2:

> Profile: A construct where information about the learner or activity is kept, typically in name/document pairs that have meaning to an instructional system component.

Currently in 1.0.3:

> Profile: A specific set of rules and documentation for implementing xAPI in a particular context. Profiles generally provide a particular vocabulary of terms, some created specifically for the profile, and some are referenced from other vocabularies. Sometimes a profile might provide multiple vocabularies for different situations, and sometimes someone might curate a vocabulary from multiple sources without creating a profile.

Perhaps we need to list both meanings and explain the difference.

**Comment by andyjohnson** [comment]
I agree!

**Comment by oconnetf** [comment]
I have never personally thought of "Agent Profile" and "Activity Profile" as conflicting with "profile" in the sense of SCORM profile and CoP profiles. Wouldn't it make more sense to treat each of the agent and activity versions as atomic?

**Comment by garemoko** [comment]
@oconnetf I think that probably makes sense in the body of text (and suspect we already do this). I do think we need to disambiguate in the definitions section anyway though.

**Comment by oconnetf** [comment]
Hmm. To me, that actually creates additional confusion. But that's just one reviewer's opinion...

**Comment by fugu13** [comment]
I'd broadly agree with @oconnetf; trying to define two things when we really only use bare profile one way is likely to lead to more confusion, not less.

What do people think about giving definitions for Profile and Document Profile Resource?

**Comment by garemoko** [comment]
@fugu13 I think that approach would work so long as we also: 

* Use the term 'Document Profile Resource' in all the right places
* Reference the definitions to one another (e.g. "Not to be confused with...")

**Comment by oconnetf** [comment]
@garemoko: Where did "Document Profile Resource" come from?

**Comment by garemoko** [comment]
@oconnetf I took it from @fugu13 [above](https://github.com/adlnet/xAPI-Spec/issues/967#issuecomment-238967539), but the rationale is that we use the terms Agent Profile Resource and Activity Profile Resource, Document Profile Resource would be a collective term for the two. (Document Resource is the term for all three where the State resource is included)
