### ISSUE TITLE
Verify the About Graphics Text still make sense

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#968]
The graphical updates have been approved, but make sure the text aligns with what is in the graphics now.

**Comment by garemoko** [comment]
> but shouldn't be viewed as boundaries or even "the norm".
This phrase doesn't make a lot of sense in the sentence it's in.

> one or more Learning Record Stores (LRS)
Should be LRSs.

> The Learner has an account on the LRS/LRSs. The Learning Record Store has authentication and authorization responsibilities with each party.
This doesn't fit well with "which stores these records about the learner".

Figure 2 and 3 text fits with the graphics. 

One other thing I noticed when reviewing this is that we don't actually label the graphics figure 1, 2 and 3. We should do that.

**Comment by andyjohnson** [comment]
Good catches!
