### ISSUE TITLE
Verbs/CoP: ADL Companion

### ISSUE THREAD

**Issue by oconnetf** [adlnet/xAPI-Spec#979]
Should [this](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#description-8) say "maintains" rather than "is creating" and link to [this](https://github.com/adlnet/companion-specification-for-xapi-vocabularies)?

**Comment by garemoko** [comment]
I couldn't see anything in the companion relating to versions or releases but I'm reasonably sure I remember @jhaag75 sharing it somewhere. 

@jhaag75 can you confirm that this should be considered released?

**Comment by jhaag75** [comment]
good catch! yes, totally agree

**Comment by oconnetf** [comment]
@jhaag75, should a patch link to the GitHub repo directly or to [the GitBook version](https://adl.gitbooks.io/companion-specification-for-xapi-vocabularies/content/)?

**Comment by jhaag75** [comment]
Either is fine, but I think the gitbook is more reader-friendly than
github.

-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by oconnetf** [comment]
Gah. Never mind. In the development version, that section is gone for verbs. It's been reworked appropriately in other places.
