### ISSUE TITLE
List "the wrong data type" in  Formatting Requirements

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#982]
In: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#dataconstraints

See: https://github.com/adlnet/grail-issue-tracker/issues/27

Propose changing:

- with strings where numbers are required, even if those strings contain numbers.
- with strings where booleans are required, even if those strings contain booleans.

To:

- where the wrong data type is used e.g. with strings where numbers are required, even if those strings contain numbers or with strings where booleans are required, even if those strings contain booleans.

**Comment by andyjohnson** [comment]
Totally agree this is important.  I'd say any argument that this requirement has drastically changed can be checked by the fact that when a data type is given, the expectation of it being followed is at the MUST level.
