### ISSUE TITLE
Prefer "Total Learning Architecture" to "Training and Learning Architecture"?

### ISSUE THREAD

**Issue by oconnetf** [adlnet/xAPI-Spec#988]
The original source of the initialism "TLA" is still referenced [here](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/CONTRIBUTING.md#adls-role-in-the-experience-api). Per the focus areas listed [here](https://www.adlnet.gov/adl-research/), should it be updated for 1.0.3?

**Comment by garemoko** [comment]
Interesting. It definitely *was* Training and Learning Architecture.

**Comment by oconnetf** [comment]
Yep. Time to prepare for the future!

**Comment by aaronesilvers** [comment]
I for one welcome the TOTAL Learning Architecture RECALL.
#getyourlearningarchitecturetomars
